cleanflight/cleanflight

src/main/io/serial_cli.c
rssi_scale parameter was declared as unsigned int but treated as int.
=> Correction of bug issue#312

src/main/rx/rx.c
map AETR1235 will result in buffer overflow
=> fix index overflow in channel mapping

docs/Buzzer.md
There was a broken link caused by a typo in 'docs/Buzzer.md'.
=> Fix broken link in Buzzer.md.

src/main/config/config.c, src/main/flight/flight.c, src/main/flight/flight.h, src/main/io/rc_controls.h, src/main/io/serial_cli.c, src/main/io/serial_msp.c, src/main/mw.c, src/main/mw.h
This code uses a stick position algorithm for calculating the leveling force when inverted.  This is based on RC911's "Stick Mixing" algorithm on the KK2 controller, and is similar to the horizon mode in PID controller 0.  
Flight test is here:
https://www.youtube.com/watch?v=C_vZDNst6pM
When tuning, the Level P term is the leveling force when in angle mode.  The Level I term is the leveling force when in horizon mode, and the Level D term is the percentage of stick travel where leveling is active.  The default values seem to work fine.
=> Baseflight pid (pid_controller=2) horizon mode tuneup

src/main/rx/rx.c
An example is when a GPS is being used on UART2 (Rx pin 4), with the mapping of AET4R123.  This code prevents failsafe being triggered by GPS data on Rx pin 4.
=> Bugfix for failsafe ignoring RX signal mapping

src/main/target/STM32F3DISCOVERY/target.h
LSM303DLHC compass is compatible to the HMC5883L. This was an easy one.
=> Add LSM303DLHC compass support using HMC5883L driver

src/main/drivers/adc_stm32f10x.c
ADC clock speed may be slightly higher, but there is no benefit in current code
stm32f303 code does set prescaler correctly (but quite low)
=> Fix ADC clock speed to be within specification

src/main/common/maths.h
This macro was used literally nowhere in the codebase.
=> Removed unused DEG2RAD macro.

src/main/common/maths.h
Review this request first: https://github.com/cleanflight/cleanflight/pull/397, then only compare new changes onto that one, or ask me to rebase :)
The RADX10 macro is literally not used anywhere.
=> Removed unused RADX10.

src/main/common/maths.h, src/main/config/config.c, src/main/drivers/accgyro_spi_mpu6000.c, src/main/drivers/accgyro_spi_mpu6500.c, src/main/flight/imu.c, src/main/flight/imu.h, src/main/flight/navigation.c, src/main/main.c, src/test/Makefile, src/test/unit/flight_imu_unittest.cc
Review this request first: #403 Sw, then only compare new changes onto that one, or ask me to rebase :)
Switched to the naming scheme verb-thing for imu methods, like initIMU, calculateIMU etc, and also changed to IMU all caps instead of it being different everywhere.
=> Imu naming

src/main/startup/startup_stm32f30x_md_gcc.S
This fix will allow to invoke the bootloader with the CLI "R" command for STM32F3 based targets. Fix for issue #412 .
=> Fix bootloader mode for STM32F3 targets

src/main/mw.c
Fixes #426 (tested on my quad that has a barometer present)
=> Fix bug that allowed arming craft before gyro calibration completed

src/main/io/serial_cli.c, src/main/sensors/battery.h
If you use an ACS756 current sensor in reverse you need to be able to set negative current scales and an offset which is 2.5V. This was not possible before. I'll do a pull request which allows these values for https://github.com/cleanflight/cleanflight-configurator as well.
=> Add support for current sensors with a negative scale

src/main/io/serial_msp.c
The first commit corrects some message lengths. It would be a good idea to have tests for the message lengths.
The second commit enhances ```MSP_CURRENT_METER_CONFIG``` and adds ```MSP_VOLTAGE_METER_CONFIG```. These changes are needed to get rid of ```MSB_BF_CONFIG```.
=> Change current meter msp command

src/main/io/serial_msp.c
Use signed value normally, truncate to 0-0xffff when multiwiiCurrentMeterOutput is active
=> Send current meter reading as signed value

docs/PID tuning.md, src/main/flight/flight.c, src/main/io/serial_cli.c
Finally ported the Harakiri PID controller algorithm.
From the documentation:
PID Controller 5 is an port of the PID controller from the Harakiri firmware.
The algorithm is leveraging more floating point math. This PID controller is also compensates for different looptimes on roll and pitch. It likely dont need retuning of the PID values. Actually there are two settings hardcoded which are configurable via the GUI in Harakiri:
OLD_YAW 0 // [0/1] 0 = multiwii 2.3 yaw, 1 = older yaw.
MAIN_CUT_HZ 12.0f // (default 12Hz, Range 1-50Hz)
The PID controller is flight tested and running well with the default PID settings. If you want do acrobatics start slowly.
Yaw authority is also quite good. 
Blackbox code for yaw need some fixes. I need to sort out the different controller parameters (P, I, D …
=> Harakiri PID controller

src/main/flight/flight.c
Previously nothing was logged since the intermediate calculations were floats. Logging them converted to integers is better than nothing.
=> Blackbox: Log PID intermediates for pidLuxFloat

src/test/unit/battery_unittest.cc
=> Avoid reading uninitialised memory during battery unit tests

docs/Board - AlienWii32.md, src/main/target/ALIENWIIF3/target.h, src/main/target/NAZE/target.h
Please can we also add the HEX for the ALIENWIIF3 target to the next release. Thanks.
BTW: here is an picture of an AlienWii32 F3 prototype:
http://www.multiwii.com/forum/viewtopic.php?f=12&t=4893&p=61295#p61295
=> ALIENWII F3/F1 target cleanup and documentation update

src/main/flight/autotune.c, src/main/rx/sbus.c
I was having some issues using the debug[] vars and it turned out that some were being written to by default.  I thought that fixing that might save someone else the time tracking them down.
=> Disable debug vars by default

src/main/io/serial_cli.c, src/main/sensors/acceleration.h, src/main/sensors/compass.h
The upper bound on these variables has been too small since 1.7.2 (which moved the previous maximum NONE value to below the last entry).
=> Fix upper limit on mag_hardware and acc_hardware CLI variables

src/main/flight/mixer.c
The yaw servo now reverses when the throttle is lower than the midpoint.
Flight tested OK.
In reference to https://github.com/cleanflight/cleanflight/issues/548
=> Bugfix for 3D inverted flight using a tricopter.  

Makefile, src/main/blackbox/blackbox.c, src/main/common/utils.h, src/main/config/config.c, src/main/drivers/adc.c, src/main/drivers/adc_impl.h, src/main/drivers/adc_stm32f10x.c, src/main/drivers/adc_stm32f30x.c, src/main/drivers/bus_i2c_stm32f10x.c, src/main/drivers/inverter.h, src/main/drivers/light_led.h, src/main/drivers/pwm_mapping.c, src/main/drivers/serial_uart.c, src/main/drivers/serial_uart.h, src/main/drivers/serial_uart_impl.h, src/main/drivers/serial_uart_stm32f10x.c, src/main/drivers/serial_uart_stm32f30x.c, src/main/drivers/system.c, src/main/io/serial.c, src/main/io/serial_cli.c, src/main/main.c, src/main/sensors/battery.c, src/main/telemetry/frsky.c, src/main/telemetry/hott.c, src/main/telemetry/smartport.c, src/test/unit/battery_unittest.cc
Here are some improvement that accumulated in my 'local' branch. The changes are mostly stylistic, code functionality should not be modified, except:
- i2c interrupts are disabled sooner on error
- fixed typo in serial_uart_stm32f30x.c
- some conditional compilation is added
- 4096 is used instead of 4095 in ADC scaling
=> Port changes

src/test/unit/battery_unittest.cc
batteryConfig initialization was merged twice.
=> Fix incorrect merge in battery_unittest

src/main/flight/imu.h
int8_t small_angle prevents using angles>128deg (and thus disabling it with small_angle=180)
=> Fix small_angle type to match CLI

docs/Cli.md
There shouldn't be a space in the 'rateprofile n' command
=> Typo fix for rate export commands in cli.md

src/main/io/rc_controls.h, src/main/io/serial_msp.c
Since some people are indeed using yaw > 1.0 (noted on RCGroups).
Also fixes bug in my merged commit where the SET_RC_TUNING message wouldn't be read properly due to the expansion of the MIN() macro.
=> Restore previous rate limit for yaw of 2.55

src/main/blackbox/blackbox_io.c, src/main/config/config.c, src/main/drivers/serial.h, src/main/drivers/serial_softserial.c, src/main/drivers/serial_softserial.h, src/main/drivers/serial_uart.c, src/main/drivers/serial_uart.h, src/main/drivers/serial_uart_impl.h, src/main/drivers/serial_uart_stm32f10x.c, src/main/drivers/serial_uart_stm32f30x.c, src/main/io/serial.c, src/main/io/serial.h, src/main/rx/sbus.c, src/main/telemetry/frsky.c, src/main/telemetry/smartport.c, src/main/telemetry/telemetry.h, src/test/unit/telemetry_hott_unittest.cc
Whoops, accidentally added this branch to the Cleanflight repo rather than my own repo! Anyway, this separates out port options from the port "mode" field. Port options are inversion, stop bits and parity.
Tested:
* FrSky telemetry on Softserial (softserial inversion)
* Blackbox at 230400 on UART1 (2 stop bits option)
* Blackbox at 250000 on UART1 (default options)
* CLI, MSP etc on UART1 (default options)
Expected to work:
* Smartport, since the code is the same as FrSky telemetry which works
Untested:
* SBus (2 stop bits, inversion, even parity). I don't have the hardware to test this myself.
=> Add new serial port options field (inversion, stop bits, etc)

src/main/drivers/pwm_mapping.c
When LED_STRIP feature is enabled on NAZE32 and gimbal_flags is set to 4 (to forward AUX1-4 to PWM5-8), no PWM waveforms appear on outputs PWM5-8.  This is because the LED driver uses timer TIM3 (also needed for PWM5-8).  As a workaround, this patch will route AUX1/AUX2 to PWM13/PWM14 (channels 5/6 of the headers that connect to ESCs).
=> fix for missing AUX1-4 signals on PWM5-8 outputs with LED_STRIP on NAZE

src/main/flight/pid.c
The default tuning range for the LuxFloat PID controller is not high enough, meaning that even with the max value in the GUI, it's not possible to get enough I effect.  This change simply multiplies this value by ten, which allows the I component to be tuned effectively.
=> ^ Multiplying LuxFloat I term by ten to make it tuneable

src/main/drivers/timer.c
Should fix problem with PPM. The code is still broken (race conditions), but this should bring error probability low enough.
=> Fix PPM in TIM1

docs/Blackbox.md, src/main/drivers/flash.h, src/main/drivers/flash_m25p16.c
Adds support for Winbond W25Q64 64mbit flash, though it doesn't fit on the board without bending pins due to being a little too wide. A couple of users have installed it successfully, here's what it looks like installed on hdphilip's board:
=> Add support for Winbond 64Mbit SPI flash chip

docs/Board - AlienWii32.md, docs/Board - Sparky.md, src/main/config/config.c, src/main/target/ALIENWIIF3/target.h, src/main/target/SPARKY/target.h
Voltage monitoring is tested for an AlienWii32 F3 prototype. For Sparky it should also work. Documentation is updated accordingly.
This is related to issue #523
=> Enable battery monitoring for Sparky and ALIENWII F3

src/main/io/serial.c, src/main/io/serial.h, src/main/main.c
Closes #701 
(MSP still tries to open the softserial port it is erroneously configured for, but now the open harmlessly fails and it doesn't try to use the port further)
=> Don't allow softserial ports to be opened if softserial isn't enabled

src/main/drivers/serial_uart.c, src/main/drivers/serial_uart_stm32f30x.c, src/main/target/SPARKY/target.h, src/main/telemetry/smartport.c
SBUS + SPORT works on Sparky + FrSky X8R (UART2 sbus; UART3 sport, with `set telemetry_inversion = 1`)
=> Fix sparky smartport

docs/Gps.md
Used to be a Hobbyking label that pointed to an eBay link.
=> Fix vendor reference in GPS hardware table

src/main/mw.c, src/main/telemetry/frsky.c, src/main/telemetry/frsky.h, src/main/telemetry/telemetry.c, src/main/telemetry/telemetry.h
using calculateThrottleStatus this time, send 0 as RPM when THROTTLE_LOW and
MOTOR_STOP.
rxConfig and deadband3d_throttle are passed from mw.c through telemetry.c
closes #562 
replaces original PR (#577) which I've closed
=> FrSky RPM Telemetry Motor_Stop Bugfix

src/main/sensors/barometer.c
Delays between baro calls are modified to always take at least specified amount of time
=> fix barometer timing code

src/main/config/config.c, src/main/io/serial_cli.c, src/main/telemetry/hott.c, src/main/telemetry/telemetry.c, src/main/telemetry/telemetry.h, src/test/unit/telemetry_hott_unittest.cc
This alarm is for battery voltage in **EAM** Hott telemetry **binary** mode. 
It is triggered when the battery voltage becomes lower than the warning battery level.
The period of the alarm sound is set under CLI : parameter *Hott_alarm_sound_period* (default value is 5s) up to 120s.
On the Hott TX, the sound is either a beep, or a voice alarm ("under voltage") when using earphones. The *Batt1* value blinks accordingly on the TX display.
=> HoTT battery alarm

src/main/io/serial_cli.c
When the profile being used isn't zero, this patch fixes memory corruption when restoring CLI dumps, and fixes ability to read/write `yaw_direction`, `tri_unarmed_servo`, `servo_lowpass_freq` and `servo_lowpass_enable` variables on the CLI.
Closes #766
=> Fix CLI: mixer settings should be master values, not profile values

src/main/flight/altitudehold.c
This uses the raw stick values instead of the calculated RCCommand values to determine whether or not the stick has moved.  The problem was that the RcCommand variable wasn't being reset to the stick position each loop, and so outputs were being treated as inputs.
=> Bugfix to stop altitude hold drift, especially noticeable in sonar mode.

src/main/telemetry/smartport.c
Correct voltage calculation for smartport telemetry
see also:
https://github.com/cleanflight/cleanflight/commit/0000d3e65e85b3d31412b0125a336618c6aac686#commitcomment-10682832
=> fix voltage calculation for smartport telemetry

src/main/mw.c
The changes made in 1.8.0 to support `pid_at_min_throttle` prevented `tri_unarmed_servo=1` from having any effect. Here's what the yaw control worked like on 1.7.2:
<table>
<tr><th colspan="5">Is yaw control of the tricopter allowed? 1.7.2</th></tr>
<tr><th></th><th colspan="2">Disarmed</th><th colspan="2">Armed</th></tr>
<tr><th></th><th>Throttle low</th><th>Throttle normal</th><th>Throttle low</th><th>Throttle normal</th></tr>
<tr><td rowspan="2">tri_unarmed_servo = 0</td><td>No</td><td>No</td><td>Yes</td><td>Yes</td></tr>
<tr><td>No</td><td>No</td><td>Yes</td><td>Yes</td></tr>
<tr><td rowspan="2">tri_unarmed_servo = 1</td><td>Yes</td><td>Yes</td><td>Yes</td><td>Yes</td></tr>
<tr><td>Yes</td><td>Yes</td><td>Yes</td><td>Yes</td></tr>
</table>
The current behaviour on 1.8.1 is …
=> Fix tri_unarmed_servo (was broken by pid_at_min_throttle changes)

build_docs.sh, docs/README.md
The guide explains the basic setup steps a CF noob should follow, linking to individual docs. The rest of the docs (the advanced ones) are listed and linked at the bottom.
I know more work needs to be done, but I'm still a CF noob so I will refrain until I have some xp. Others can chip in.
The TODO list in the beginning should be incorporated elsewhere I guess, but I don't know how the project todos are managed/stored.
=> Added a how-to-setup-everything walkthrough guide as a README file

docs/development/Building in Eclipse.md, docs/development/Hardware Debugging in Eclipse.md, docs/development/Hardware Debugging.md
Since the documentation is all located in the docs folder and only the Buidling in Eclipse and Hardware Debugging pages are in the wiki, it would be nice to consolidate the information on hardware debugging.
This would move all wiki content to the docs/development folder.
=> Move wiki pages to docs folder

src/main/config/config.c, src/main/flight/mixer.c, src/main/flight/mixer.h, src/main/flight/pid.c, src/main/flight/pid.h, src/main/io/serial_cli.c
The hardcoded limit in the mixer and PID controllers 3-5 would be removed
by default and will be configurable by CLI variables:
yaw_jump_prevention_limit, global setting (original fixed value was 100)
yaw_p_limit, per profile setting (fixed value was 300)
The following CLI commands will set the exact behavior as before the change if there is someone relying on this limiters.
set yaw_jump_prevention_limit = 100
set  yaw_p_limit = 300
=> This fix is for avoiding yaw overshoot and bounce back for some configurations

docs/Buzzer.md, docs/Cli.md, src/main/io/beeper.c, src/main/io/beeper.h, src/main/io/serial_cli.c
Added 'play_sound' CLI command, which may be used to demonstrate the buzzer tones. Repeatedly entering the command will play the various tones in turn. Entering the command with a numeric-index parameter will play the associated tone.
Improved ACC_CALIBRATION_FAIL sound (to make it less like ACC_CALIBRATION sound).
Updated docs.
--ET
=> Add 'play_sound' CLI command

src/main/mw.c
Fixes #824
This restores the 1.7.2 yaw behaviour for aircraft.
=> Allow yaw at low throttle for airplane mixes

src/main/drivers/barometer_bmp085.c
Prevents bmp085 interrupts being set up when no bmp085 is present so the board will boot correctly.
Also removed delay(20) as there is already a delay(100) in main.c
Tested on an acro board but not on a board with a baro.
=> Fix for some 1.9.0 boards not booting up

docs/Sonar.md, src/main/main.c, src/main/sensors/sonar.c, src/main/sensors/sonar.h
Check if ADC current sensor is enabled in sonarInit() and change sonar pins to pwm 5 and 6 if it is. Same as when RX_PARALLEL is enabled.
=> Updates sonar so that it can be used together with ADC current meter

src/main/target/NAZE/target.h
AlienWii F1 variants don't have an voltage divider. Disable feature
VBAT.
=> AlienWii F1 VBAT fix

src/main/io/rc_curves.c
Currently uses PITCH_LOOKUP_LENGTH when generating the yaw curve and should be using YAW_LOOKUP_LENGTH.
=> Corrected YAW_LOOKUP_LENGTH

src/main/drivers/accgyro_mpu6050.c
Page 17 of the MPU6050 datasheet states that the PLL Settling Time is typ 1ms and max 10ms.  Gyro values are undefined during this period.  Gyro values should not be read within 10ms, max, after changing CLK_SEL.
=> Added MPU6050 PLL Settling Time delay

docs/PID tuning.md, src/main/flight/pid.c, src/main/flight/pid.h, src/main/mw.c
Pid controller 1  and 2 became really popular and there are many requests for TPA implementation.
As the regular coupled principles can't be applied to this PID controller there is only PID reduction being done without coupling.
Check the code and give me some feedback of what you think.
=> PID1 and PID2 TPA Support Added

src/main/flight/pid.c
Due to this request:
cleanflight#840
I ported the logic from PID2 into PID1 for the horizon code with modifications for integer instead of floats. Also Level D term is here being used for Horizon Sensitivity.
Default value of 100 equals to 80% sensitivity, which should be fine!
Also the horizon leveling is shifted by 4 to make the default Level I term more usable.
It has been flight tested and it works really well!
=> PID1 Horizon Mode Fixed

.travis.sh
Previously the words in the centre of a underscores_inside_words compound would be wrapped in &lt;em&gt; tags and the underscores would be removed, this fixes that by tweaking the Markdown dialect.
Fixes #860
=> Patch Gimli to fix underscores_inside_words in PDF manuals

src/main/io/serial_cli.c
Prepended the version string with a # to avoid the CLI from interpreting the version string as a command when pasting a dump file back (restore in CLI). It is the __only__ line written by the dump command that is not a command but does not start with a #.
Strip comments starting with `# comment` from lines. This is to allow adding (per line) comments to CLI dumped backup files. For this i have an automated addition of comments and/or manual comments by the user in mind.
=> Some mods to CLI command interpretation and output

src/main/telemetry/frsky.c
After 802218b77bcbcb5ec6d805577998067720c975df, changes a missed invocation of sendFakeLatLong(bool) to sendFakeLatLongThatAllowsHeadingDisplay().
Fixes spelling in sendFakeLatLongThatAllowsHeadingDisplay function name.
=> Tidy up the fake lat/long heading tidyup

src/main/flight/pid.c
Slightly modified code to change the behaviour of the highest and the lowest selectable value for Angle Level D term, which is used for Horizon Sensitivity
Flight tested through the entire Level D range
=> Fix for extreme D level term PID1 Horizon

src/main/io/serial_msp.c
TELEMETRY_BOX mode is not available in the GUI following setting telemetry_switch=1 with feature TELEMETRY enabled.  
This is a simple correction to the brace location to restore the intended logic and make TELEMETRY mode available in the GUI if telemetry_switch is set to 1.
=> Telemetry_Switch TELEMETRY_BOX conditional logic incorrect

lib/main/CMSIS/CM3/DeviceSupport/ST/STM32F10x/system_stm32f10x.c, lib/main/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c, src/main/io/display.c, src/main/io/serial_msp.c, src/main/version.c, src/main/version.h
This patch moves more constant data out of RAM and into flash, and re-works the MSP serialisers to save code space.
Saves about 180 bytes of flash and ~300 bytes of RAM.
=> various: optimise RAM and flash usage

docs/development/PID Internals.md, src/main/blackbox/blackbox.c, src/main/blackbox/blackbox.h, src/main/drivers/accgyro_l3g4200d.c, src/main/drivers/accgyro_l3gd20.c, src/main/drivers/accgyro_lsm303dlhc.c, src/main/drivers/accgyro_mpu3050.c, src/main/drivers/accgyro_mpu6050.c, src/main/drivers/accgyro_spi_mpu6000.c, src/main/drivers/accgyro_spi_mpu6000.h, src/main/drivers/accgyro_spi_mpu6500.c, src/main/flight/imu.c, src/main/flight/imu.h, src/main/flight/pid.c, src/main/io/serial_msp.c, src/main/mw.c, src/main/sensors/initialisation.c
With reference to PR #815 there are some valid reasons for removing yaw gyro smoothing from imuUpdate .
1. This is an unnecessary, special, case for Tricopters which appears to be left over from an early "analogue servo workaround".
2. This smoothing is not required for digital servos (therefore, it disadvantages tricopters with digital servos).
3. The yaw gyro smoothing is hidden from the Tricopter pilot who has no control over it.
4. This smoothing should be applied on the servo output using servo lowpass filtering.
5. This smoothing is common to all PID controllers and may further improve issue #741 for tricopters.
6. The Blackbox logs show vast improvment to the PID sums which is also noticed in flight.
7. This smoothing forces lower P gain.
8. Removal simplifies the code.
9. This …
=> Remove tricopter yaw gyro smoothing from imuUpdate

src/main/config/config.c, src/main/config/config.h, src/main/drivers/pwm_mapping.c, src/main/drivers/pwm_output.c, src/main/drivers/pwm_output.h, src/main/flight/mixer.c, src/main/flight/mixer.h, src/main/io/serial_cli.c, src/main/io/serial_msp.c, src/main/main.c, src/main/mw.c, src/test/unit/flight_mixer_unittest.cc, src/test/unit/rc_controls_unittest.cc
This is to resolve issue #358 including the delay for oneshot feature changes on reboot, and is a replacement for earlier PR #893.
Instead of trying to latch the desired features and apply them after a soft reset (which also required an additional write to flash), it is now such that:
* The active features are latched after initialization completes and not modified until the next startup.
* The latched features are used  by `feature()` to report what feature is active.
Changes to features ordered via MSP or CLI commands are applied to the configuration that gets saved to flash. This guarantees that all saved modifications are persistent even when power is switched off.
Prior to a soft reset, the latched (active) features and the currently configured features are used to detect if the …
=> System - Lock active features after init

src/main/config/config.c, src/main/flight/mixer.h, src/test/unit/flight_mixer_unittest.cc
remove multiple declaration of the function mixerUseConfigs, so if get modified and you don't update all the callers you get a compilation error instad of segfault
=> removed multiple declaration of function mixerUseConfigs

src/main/mw.c
When using an AUX switch to enable telemetry, it doesn't send telemetry until armed. This PR tries to fix this.
With this PR, as soon as AUX is enabled, telemetry kicks in independently of the arm status. When AUX is disabled, port is reconfigured again for the shared function (if any).
=> Telemetry switch enable independent of arm status

src/main/telemetry/smartport.c
- Suppress messages for disabled features and unavailable sensors (save bandwidth and clutter/storage on OpenTX 2.1)
- Fix stray responses to outdated requests from the receiver (sometimes especially shortly after boot the board would be too slow to service incoming serial data, and subsequent parsing of the buffer would trigger a request when the receiver had already sent IDs other than the one the board is supposed to answer to, leading to the board stepping over someone else's slot and being detected as a new sensor).
- A smart port request is only valid for a few ms, so the current way of looping through the ID list was not valid. One solution would be to just discard the slot and wait for the next one, the other is to loop straight away while we're there. I implemented the latter as …
=> SmartPort - Some fixes

src/main/config/config.c
New Cleanflight default is now the same.
=> Remove failsafe_trottle setting from AlienWii32 defaults

src/main/startup/startup_stm32f10x_hd_gcc.S
new contents as per
/lib/main/CMSIS/CM3/DeviceSupport/ST/STM32F10x/startup/gcc_ride7/startup_stm32f10x_hd.s
=> correct startup_xxx.S contents for HD devices (was for MD before)

docs/Blackbox.md, src/main/drivers/flash.h, src/main/drivers/flash_m25p16.c
Support for the following SPI Flash Memorys:
* Micron N25Q0128 - 128 Mbit (not tested but should also work)
* Winbond W25Q128 - 128 Mbit (tested)
=> Support for 128Mbit SPI flash

lib/main/STM32_USB-FS-Device_Driver/inc/usb_regs.h
Fixes the LTO build with GCC 4.9.  Tested on the STM32F3DISCOVERY.  I
assume the compiler was doing cross function optimisation, saw that
the same non-volatile address was read twice, and dropped the second
read.
Fixes #763.
Signed-off-by: Michael Hope <mlhx@google.com>
=> usb: mark register accesses as volatile.

src/main/flight/mixer.c
Fixed a bug: in 3D mode to stop the motors, send neutral3d value to the ESCs instead of mincommand.
This was causing the motors to go full negative for a short time everytime I left the CLI mode tab in the Configurator GUI.
=> Bug Fix: Stop motors in 3D mode

.travis.sh, .travis.yml, docs/development/Travis.md
* cleaned up curl parameter handling
* added a maximum of 10 retries for publishing builds to the CI server and fetching toolchains
* limited retries to 2 minutes of total time
* do not show the build as broken if curl eventually fails to upload the build artifacts.
* updated GCC 4.8 -> 4.9
=> Travis/CI Updates: retry failed HTTP requests, Updated GCC to 4.9-2015q2

src/main/config/config.c, src/main/flight/mixer.c
(Sorry, still learning the ways of Github. Let me do this again.)
Assuming motors are arranged in the typical format of equidistant around a circle, the mixer values for octo flat X seem to have been incorrect since MultiWii. Before and after:
=> Corrected default mixer values for octo flat X

src/main/drivers/barometer_bmp085.c, src/main/drivers/barometer_bmp085.h, src/test/Makefile, src/test/unit/baro_bmp085_unittest.cc, src/test/unit/platform.h
Tests the pressure and temperature calculations.
Uses the data that can be found in the bmp085 datasheet.
Also tests when oversampling is set to 3 and at extremes of temperature (-20 and 55 degC).
=> Unit tests for BMP085

src/main/drivers/barometer_ms5611.c, src/test/unit/baro_unittest.cc
Unit test for first and second order calculations.
Revealed two issues.
1. Second order compensated temperature was not calculated correctly.  This is less of an issue as it's not used in any flight control - as far as I can see.
2. Temperature (temp) needs to be an int64_t not int32_t.  Not sure this would cause flight issues for the temperatures ranges expected.
Unit test for pressure calculations based on MS5611 data sheet.
Built a spread sheet to test the unit test inputs which can be found here:
http://www.rcgroups.com/forums/showthread.php?t=2446649#post32001452
=> MS5611 unit test for pressure calculations

src/main/blackbox/blackbox.c, src/main/blackbox/blackbox_fielddefs.h, src/main/blackbox/blackbox_io.c, src/main/blackbox/blackbox_io.h, src/main/io/rc_controls.c
Logging of the inflight adjustments to the blackbox. PR has been cleaned up and squashed. 
Thanks BorisB for the tip about branches and Nick for useful tips and general patience. 
Some screenshots:
Constant incrementing of the RollP leads at certain point to severe oscillations
=> Add logging of the inflight adjustment events to the blackbox

build_docs.sh
I think the PDF version of the manual would benefit from a table of contents. Fortunately this can be auto generated by passing wkhtmltopdf options to gimli.
=> Add a simple TOC to the front of the PDF manual

Makefile
This makes developing against Discovery boards easier.
=> build: add a target for flashing via st-flash.

src/main/config/config.c, src/main/io/serial_cli.c, src/main/io/serial_msp.c, src/main/rx/rx.c, src/main/rx/rx.h
~~With this PR users can set an individual value for each RX channel, that will be used in case of an RX lost. I added a CLI command `rxfail` to set these values. Mapping for channels is taking into account, so when channel 0 is set to 1000, this value will be used for A in default mapping and for T in JR map.~~
~~I did not yet added MSP commands.~~
EDIT:
The intention of this PR is to cover (RX faisafe state) safety independent of failsafe handling.
In other words: What does the flight controller do when you forget to switch your transmitter on or a wire comes loose, has radio interference etc. (even when failsafe handling is disabled).
Please see the commit message(s) for latest implementation details.
=> RX - Added programmable RX channel defaults on RX lost

docs/Blackbox.md, docs/Modes.md, src/main/blackbox/blackbox.c, src/main/blackbox/blackbox_fielddefs.h, src/main/blackbox/blackbox_io.c, src/main/blackbox/blackbox_io.h, src/main/common/maths.c, src/main/common/maths.h, src/main/io/rc_controls.c, src/main/io/rc_controls.h, src/main/io/serial_msp.c
Initial implementation by @fedorcomander in #1122.
You can now add a mode switch to enable Blackbox logging. If no Blackbox mode is defined, the old behaviour remains (always log), otherwise log events are only logged when the mode is active.
Matching support for blackbox_decode and the web viewer has already been committed in.
=> Add pause/resume switch support to Blackbox

src/main/rx/sumd.c
=> RX - SUMD channels are received as 16 bit values instead of 32

src/main/io/serial_cli.c
Compass calibration is tricky. It is sometimes hard to get it right. This commit adds `magzero` cli variables that could be used to get compass offsets after successful calibration and set them when config gets erased for whatever reason.
=> Add ability to get/set mag calibration data

src/main/drivers/pwm_rx.c, src/main/drivers/pwm_rx.h, src/main/rx/pwm.c, src/main/rx/rx.c
@hydra This is an important update to #995.
RX hold values were not preserved and FC preset values were only applied after an initial jump to the RX failsafe preset value under the following conditions:
Use PWM. Set channels 1-4 (sticks) to failsafe OFF. Set aux channel to a preset failsafe value.
This PR has been tested with PWM, PPM and SUMD (using GR-12), in all cases FC hold function `rxfail 0 h 1600`and FC preset function `rxfail 0 s 1600` worked well.
More has changes, please see commit message for details.
=> RX - Corrections to RX fail detection, hold and preset, when using a PWM connection

src/main/rx/sumd.c
Officially the CRC check is part of the SUMD protocol.
Framing errors are already covered and i expect these to occur around
the same time as CRC errors, so i am not sure if someone will ever
notice the difference...
=> RX - Added CRC check to SUMD handler

docs/Rx.md, src/main/config/config.c, src/main/io/serial_cli.c, src/main/io/serial_msp.c, src/main/rx/rx.c, src/main/rx/rx.h
Allow rxfail to be used for all channels, not just aux channel.
Replaces and supplements #1203
=> Failsafe - Add rxfail `auto` mode.

src/main/io/serial_msp.c
Previously the P, I, D and H sensitivity for the LuxFloat PID controller were clamped to 250 on the top end when *reading* those values over MSP. 
This meant that PIDs of 255 could be set using MSP by the Configurator, but reading back those same values over MSP would show them as 250, despite the correct value of 255 being displayed correctly by `dump` on the CLI.
There shouldn't be any more clamping upon read than is needed to fit the PIDs into a byte, otherwise we will read values that aren't actually being used by the FC.
=> Fix upper bound clamping of floating point PID settings upon MSP read

Makefile
Simple clean up of duplicated ARCH_FLAGS for certain targets.
=> Remove duplicated -mfpu=fpv4-sp-d16 under cortex-m4 based targets.

Makefile
Developers will find it easier, and many expect, to run the test suite from the top level folder.
This simple feature adds `make test` in the root folder of cleanflight. Associated changes also ensure `make clean` from the root folder cleans up after itself.
Thus removing a `cd` command from the iterative process of refactoring.
=> Promote 'make test' to a top level folder feature.

src/main/config/config.c, src/main/rx/rx.c, src/main/rx/rx.h
Fixes issue #1257
The problem is caused by hardware counters (timekeeping and PPM/PWM measurement) that keep running while the firmware is frozen. The result is misinterpretation of received data.
EEPROM read & write now call a suspend and resume function to make RX ignore incoming wrong data during reads/writes (and flush the wrong data on resume).
=> Fix false RX loss detection on EEPROM read/write

src/main/io/serial_cli.c
The limits for RATE were bad, so we had a "Parse error" when changing rate values other than 100.
=> Fixing servo command parsing of "rate" field

docs/Failsafe.md, src/main/config/config.c, src/main/config/config.h, src/main/config/runtime_config.h, src/main/flight/failsafe.c, src/main/flight/failsafe.h, src/main/io/display.c, src/main/io/rc_controls.h, src/main/io/serial_cli.c, src/main/io/serial_msp.c, src/main/main.c, src/main/mw.c, src/main/rx/rx.c, src/test/unit/flight_failsafe_unittest.cc, src/test/unit/rc_controls_unittest.cc, src/test/unit/rx_ranges_unittest.cc, src/test/unit/rx_rx_unittest.cc
__This pull request is to replace and add all the features (and some more) of #185__
* Added a Failsafe flightmode.
* Added AUX switch (RC controlbox) to manually activate failsafe mode.
* Prevent arming when failsafe mode via AUX switch is active (safety issue).
* Added a CLI variable `failsafe_kill_switch` for instant disarm (__KillswitchEvent__).
When set to 1 (0 is default), the failsafe switch will instantly disarm
instead of executing the auto-land procedure. Arming is NOT locked after
this, so the craft could be re-armed if needed.
This is intended for racing quads where damage and danger must be
minimized in case of a pilot error.
* Make failsafe disarm if motors armed and throttle was LOW (2D & 3D) for `failsafe_throttle_low_delay` time (__JustDisarmEvent__).
Applied code changes …
=> Failsafe - New failsafe functionality (Phase 1)

docs/Rx.md, src/main/config/config.c, src/main/io/serial_cli.c, src/main/rx/rx.c, src/main/rx/rx.h
Changed behavior of PR #1233 to make it safe. Solves issue #1254.
* Stick channels only have AUTO and HOLD mode (SET removed, which is safer).
* AUX channels now only have SET and HOLD mode (AUTO removed, did not add functionality).
* Added a rxfail parameter check in CLI.
* Modified RX documentation to reflect these changes (and more).
=> Changed behavior of PR #1233 - solves issue #1254

src/main/drivers/barometer_bmp085.c, src/main/drivers/barometer_bmp085.h
with some baro code and comments cleanup.
Fixes issue #1017
=> Test for no EOC connection allowing external I2C baro on acro boards

src/main/flight/failsafe.c, src/main/flight/failsafe.h, src/main/rx/rx.c
Modified to make mechanism use time instead of counters for call frequency independency.
Skipping RC samples uses a counter for time independency.
Also LED and beeper patterns were changed by previous implementation.
Corrected with RX supend/resume feedback to failsafe system.
__Replaces #1258 (already merged) (issue #1257)__
=> RX - Adapted implementation of RX suspend & resume on EEPROM read & write

Makefile
[Cppcheck](http://cppcheck.sourceforge.net/) is a static analysis tool for C/C++ code.
This PR adds a new command `make cppcheck` to Cleanflight.
There is an associated utility function `make cppcheck-result.xml`, which could be consumed by tools such as Jenkins.
Note: cppcheck run in this manner over Cleanflight is not fast, due to the combinatorial complexity of the many macro defines which must be examined. A slightly faster, but incomplete, run can be conducted by omitting `--force` in the arguments to cppcheck.
cppcheck has identified some code issues, which will be addressed in subsequent PRs.
=> Add command 'make cppcheck' and friend

docs/Blackbox.md, src/main/sensors/boardalignment.c, src/test/Makefile, src/test/unit/alignsensor_unittest.cc, src/test/unit/battery_unittest.cc
The unit test includes a simple independent implementation of a vector rotation. Each of the following sensor_align_e types are tested:
* CW0_DEG
* CW90_DEG
* CW180_DEG
* CW270_DEG
* CW0_DEG_FLIP
* CW90_DEG_FLIP
* CW180_DEG_FLIP
* CW270_DEG_FLIP
For each sensor_align_e type, three unit vectors and a random vector are tested.
* {1, 0, 0}
* {0, 1, 0}
* {0, 0, 1}
* {R, R, R} (where R is a random number)
The vector under test is rotated by using the functions defined in the test file and is also rotated using the sensorsAlign() function. The outputs of both are compared for equality. The outputs match for all test conditions.
=> Created Unit Tests for sensorsAlign(), addresses issue #8

src/main/io/serial_msp.c, src/main/rx/msp.c, src/main/rx/msp.h, src/main/rx/rx.c
The implementation of `MSP_SET_RAW_RC` wrote the read rc values directly into `rcData[]`. In rx.c's `readRxChannelsApplyRanges()`, these values were read from `rcData[]`, then channel mapping was applied to juggle the channels around, then the values were stored into `rcRaw[]`. In `detectAndApplySignalLossBehaviour()`, if these values were considered reasonable then they were copied back to `rcData[]`.
The issue is that if the channel mapping was not set to the identity map for MSP ("AERT1234"), and `readRxChannelsApplyRanges()` was called again before another `MSP_SET_RAW_RC` message arrived, it would read the `rcData[]` that it had already applied channel mapping to, and would apply channel mapping and channel scaling a second time. This caused channels to rapidly oscillate:
The fix is …
=> Fix RX_MSP oscillation, > 8 channel support

src/main/config/config.c, src/main/rx/rx.c
This should fix #1345, keeping the original / intended functionality as it currently is.
Proposed fix #1339 changes current behavior and does not solve the errors in initialization.
---
RX initialization/startup issue resolved:
Rx fail fallback values were wrong during init phase.
Without a (powered) receiver connected they stayed there after init.
With a powered receiver they assumed the correct state after init
(causing possible switch events on startup).
Code optimizations:
Taking expression out of the loop.
Prevent double call to function.
Eliminate function call.
Reset rcSampleIndex on rxInit().
=> RX init issue, optimization.

docs/Buzzer.md
Added description of tone sequences in document buzzer.md (issues #711 , #1096 , #1271).
As used in *io/beeper.c*.
=> Update buzzer.md with tone sequences

src/main/drivers/adc_stm32f10x.c
RSSI measurement has been broken a while ago due to a wrong indexation of DMA (swap between RSSI and External inputs).
This correction is only needed for F1 processor (in drivers/adc_stm32f10x.c). 
DMA indexation is fine for F3 (in adc_stm32f30x.c).
=> Fix incorrect DMA index for RSSI and External (F1 proc)

src/main/telemetry/smartport.c
Telemetry Smartport Current amperage is reported 10x too big.
Bug has been tested and verified on SPRacingF3 using an analog current sensor.
The SPRacinF3 was connected to an X4R-SB receiver using SBUS and Smartport.
The Telemetry was received on a Taranis and compared to a Multimeter inline with the Battery.
=> Bug Fix : Telemetry Smartport Current amperage is 10 times too big

src/main/flight/imu.c
Keep behaviour consistent with `GPS_angle[ANGLE_INDEX_COUNT]`, which is the other use of enums `AI_ROLL` and `AI_PITCH`.
Unit tests pass after this change.
=> imu: Replace MAGIC_NUMBER with proper array size reference.

src/main/config/config.c, src/main/flight/pid.c
Luxfloat PID controller was a nice concept, but very hard to tune and not as locked in as some others. After a lot of playing with different PID controllers I figured out what is good and what not.
Well this is how it should be! delta calculation was not optimal.
Please give some feedback
Updated:
- New defaults
- New delta calculation (RateError instead of GyroError)
- Removed TPA for Integral (not needed)
Flight with this PR and RC smoothing:
https://www.youtube.com/watch?v=1_SiBKD7R7M
NAZE
https://dl.dropboxusercontent.com/u/31537757/cleanflight/cleanflight_NAZE.hex
SRF3
https://dl.dropboxusercontent.com/u/31537757/cleanflight/cleanflight_SPRACINGF3.hex
CC3D:
https://dl.dropboxusercontent.com/u/31537757/cleanflight/cleanflight_CC3D.hex …
=> Luxfloat Optimisation and new defaults

Makefile
Use a one line Make fu to provide a more descriptive `make help`.
This approach adds to the existing output, by scanning through the Makefile for "## " and then printing the remaining text. Not necessary to print all options, however key ones deserve time in the spotlight.
```
$ make help
Makefile for the cleanflight firmware
Usage:
make [TARGET=<target>] [OPTIONS="<options>"]
Valid TARGET values are: NAZE NAZE32PRO OLIMEXINO STM32F3DISCOVERY CHEBUZZF3 CC3D CJMCU
EUSTM32F103RC SPRACINGF3 PORT103R SPARKY ALIENWIIF1 ALIENWIIF3
all         : default task; compile C code, build firmware
clean       : clean up all temporary / machine-generated files
flash       : flash firmware (.hex) onto flight controller
st-flash    : flash firmware (.bin) onto flight controller
unbrick     : unbrick flight …
```
=> Add new Makefile feature, try 'make help'

Makefile, docs/Gtune.md, docs/Modes.md, docs/PID tuning.md, src/main/blackbox/blackbox.c, src/main/blackbox/blackbox_fielddefs.h, src/main/config/config.c, src/main/config/runtime_config.h, src/main/flight/gtune.c, src/main/flight/gtune.h, src/main/flight/pid.c, src/main/flight/pid.h, src/main/io/rc_controls.h, src/main/io/serial_cli.c, src/main/io/serial_msp.c, src/main/mw.c, src/main/target/ALIENWIIF3/target.h, src/main/target/CC3D/target.h, src/main/target/NAZE/target.h, src/main/target/NAZE32PRO/target.h, src/main/target/SPARKY/target.h
Implement G-Tune (ported from Harakiri). Documentation can be found here:
https://github.com/MJ666/cleanflight/blob/Harakiri_PID_update/docs/Gtune.md
G-Tune is tested in a quite some test flights and is working much more saver and less intrusive than the CF Autotune. It should work on all PID controllers (PID 0, PID 3 and PID 5 are tested). Please see also here #560.
Make two formerly hardcoded parameter for the Harakiri PID configurable. The first one has helped some users with there tuning problem to eliminate some wobble.
set pid5_maincuthz = 12     [1-50Hz] Cut Off Frequency for D term of main Pid controller
set pid5_oldyw = 0          [0/1] 0 = multiwii 2.3 yaw (default), 1 = older yaw
Added an yaw constrain if yaw stick commands are given to PID 3, PID 4 and PID 5 controllers. …
=> G-Tune implementation and Harakiri pid updates

docs/Blackbox.md, src/main/blackbox/blackbox.c, src/main/blackbox/blackbox_io.c, src/main/blackbox/blackbox_io.h, src/main/drivers/serial.c, src/main/drivers/serial.h, src/main/drivers/serial_softserial.c, src/main/drivers/serial_softserial.h, src/main/drivers/serial_uart.c, src/main/drivers/serial_uart.h, src/main/drivers/serial_usb_vcp.c, src/main/io/flashfs.c, src/main/io/flashfs.h, src/main/io/gps.c, src/main/io/serial_cli.c, src/main/io/serial_msp.c, src/main/main.c, src/main/telemetry/hott.c, src/main/telemetry/smartport.c, src/test/unit/telemetry_hott_unittest.cc
This reimplements the system that Blackbox was using to throttle the write of its headers. It now:
- Adds a serial port API to tell how many bytes of tx buffer are free. This renames the old serial port API's `serialTotalBytesWaiting()` to `serialTotalRxWaiting()` and adds `serialTotalTxFree()`.
- Since Blackbox can now tell exactly how many bytes of serial and flashfs tx buffer space remains, it can avoid overflowing it
- Writes to OpenLog serial devices at no more than 6000 bytes a second, which should be enough for OpenLog to absorb 150ms of MicroSD write latency using its 900 byte buffer
- Attempts to write no faster than 64 bytes per loop iteration in order for header writing iterations to have similar runtimes to regular logging iterations
- Adds support for logging to SoftSerial …
=> Fixes truncated Blackbox headers problem with faster looptimes and slower microSD cards

src/main/flight/mixer.c
When `pid_at_min_throttle` is set to zero, this prevents the PID loop from affecting the motors while the throttle is inside the +-`deadband3d_throttle` region. In theory this could allow the motors to brake to a stop at more similar times, because the PID loop won't be trying to make attitude corrections right up until the instant that the switchover to the opposite spin direction happens.
The behaviour when `pid_at_min_throttle` is set to the default of `1` is unchanged.
Note that this has only been bench tested by me so far, never flight tested. It needs flight testing.
A Naze32 .hex file for testing can be found here:
https://github.com/sherlockflight/cleanflight-dev/releases/tag/3d-pid-at-min-throttle
Be sure to `dump` your configuration on the CLI tab before flashing this release …
=> Add support for pid_at_min_throttle = 0 for 3D flight

src/main/main.c, src/main/mw.c, src/main/rx/rx.c, src/test/unit/rx_rx_unittest.cc
Supersedes #1361
To solve problems as indicated here:
https://github.com/cleanflight/cleanflight/issues/1266#issuecomment-135640133
and here:
https://github.com/cleanflight/cleanflight/pull/1340
and here:
https://github.com/cleanflight/cleanflight/pull/1342
Tested on FrSKY X4RSB with latest CPPM firmware (non-EU version).
Firmware filename: X4R-X4RSB_cppm_non-EU_150630
In both SBUS and CPPM mode.
---
Added CLI variable `rxfail_delay` to rxfail detection
Used when out of range pulses from the receiver are detected.
Delay in deciseconds before rxfail values are applied (channel value is on HOLD until then).
Default 3 (range: 3 - 10).
This should prevent a too aggressive reaction to small dropouts.
=> RX - Improved RX failsafe detection & handling

src/main/drivers/system.c, src/main/io/serial_msp.c
Solves https://github.com/cleanflight/cleanflight/issues/1433 (see also https://github.com/cleanflight/cleanflight-configurator/issues/261)
Fixes the `Waiting for Data` problem in configurator when:
- Clicking on `Save and Reboot` button
- Clicking on `Flash Firmware`  button
When the system reboots after programming the new firmware it still
needs a connect/disconnect cycle to work normal. This cannot be solved
since the bootloader is a fixed program in ROM.
Fix is for F1 targets and only tested on naze boards.
=> Fix for Waiting for data (in configurator) problem on F1 targets

src/main/drivers/pwm_mapping.c
This modification enable servo output on CC3D in Tricopter configuration
=> Fixed servo mapping on cc3d for tricopter configuration

lib/main/STM32F30x_StdPeriph_Driver/src/stm32f30x_adc.c, lib/main/STM32F30x_StdPeriph_Driver/src/stm32f30x_hrtim.c, lib/main/STM32F30x_StdPeriph_Driver/src/stm32f30x_syscfg.c
Remove annoying warnings.
#pragma is used to minimize modification to StdPeriph_Driver source code - produced diff should be easy to handle
=> fix unused parameter warning in StdPeriph_Driver

src/main/io/ledstrip.c
Fixes Issue #1430 as reported by cppcheck.
No regressions with `make test`.
=> Correct use of sizeof(data_element) rather than sizeof(pointer)

docs/Gps.md
This change adds a brief mention of power requirements and USB power pass-through to the GPS docks. This small but important fact is not mentioned anywhere, though it is obvious if you stare at the board specific documentation long enough. Many larger flight controllers (eg Pixhawk) do pass through 5V from USB, so this is non-obvious to users of those FCs.
=> Add mention of power requirements for gpassthrough

src/main/flight/pid.c
When https://github.com/cleanflight/cleanflight/pull/1103 gets merged than this one is additional to also remove TPA from iterm of PID1 as well.
=> Remove TPA from Iterm PID1

src/main/rx/sbus.c
To solve problem mentioned here:
https://github.com/cleanflight/cleanflight/issues/1512#issuecomment-159267342
NOTE: The problem is not the main subject of issue #1512, but another observation.
__Tested with X4R-SB on Naze32.__
=> RX - Prevent SBUS receivebuffer overflow

README.md, src/main/common/atomic.h, src/main/mw.c
Changed text reference of 'baseflight' to 'Cleanflight'.
=> Fixed spelling mistakes.

src/main/io/ledstrip.c
I've noticed that function "updateLedCount" can be executed when global variable "ledConfigs" is zero, which results writing to memory at 0x0.
The call stack when this happens is:
0 updateLedCount ledstrip.c 389
1 reevalulateLedConfig ledstrip.c 403
2 applyDefaultLedStripConfig ledstrip.c 1031
3 resetConf config.c 545
4 resetEEPROM config.c 992
5 ensureEEPROMContainsValidData config.c 987
6 init main.c 154
7 main main.c 528
Looks like the function "applyDefaultLedStripConfig" reevaluates global LED config before it's initialized.
(Sorry for duplicate issue. Someone (me) didn't read docs about separate branch for pull requests)
=> fix for LED strip initialization invalid memory write

src/main/drivers/bus_i2c_stm32f30x.c
I2C OType should be set to OpenDrain (lib/main/STM32F30x_StdPeriph_Driver/src/stm32f30x_i2c.c#L31)
see #1471
This is not tested on actual hardware yet
=> Change I2C output type to OD

src/main/config/config.c, src/main/config/config_master.h, src/main/config/config_profile.h, src/main/flight/altitudehold.c, src/main/flight/imu.c, src/main/flight/imu.h, src/main/flight/mixer.c, src/main/flight/navigation.c, src/main/flight/pid.c, src/main/flight/pid.h, src/main/io/display.c, src/main/io/rc_controls.c, src/main/io/serial_cli.c, src/main/io/serial_msp.c, src/main/mw.c, src/main/sensors/sensors.h, src/main/telemetry/frsky.c, src/main/telemetry/smartport.c, src/test/Makefile, src/test/unit/altitude_hold_unittest.cc, src/test/unit/flight_imu_unittest.cc, src/test/unit/flight_mixer_unittest.cc
This PR is for merging quaternion-based IMU from my navigation-rewrite. It is flight tested on CC3D and NAZE and it gives better attitude estimation and a more locked-in feeling in ANGLE and HORIZON modes.
=> Quaternion-based Mahony's DCM IMU (initial implementation by S. Madgwick)

src/main/io/serial_msp.c
@hydra This is the change you mentioned on IRC the other day:
~~~
[22:04] <hydra_> ProDrone: if we ever support more than 18 channels we will have a problem with this:
[22:04] <hydra_> #define MSP_SET_RXFAIL_CONFIG           78 //in message          Sets RXFAIL settings
[22:04] <hydra_> #define INBUF_SIZE 64
[22:05] <hydra_> 18 * 3 = 54
[22:05] <hydra_> just so you're aware.
[22:05] <hydra_> a different approach is taken for things like the LED_STRIP configuration, etc.
[22:06] <hydra_> an index is supplied with the data. and one message is set for each index that needs to be sent.
[22:07] <hydra_> in an alternative world the FC would then be sent up to 18 rxfail messages, each with an index and 3 extra bytes payload
[22:07] <hydra_> no worries.  might be worth doing this now before the …
=> MSP_SET_RXFAIL_CONFIG changed to allow more future RX channels

src/main/common/filter.c, src/main/common/filter.h, src/main/config/config.c, src/main/flight/pid.c, src/main/flight/pid.h, src/main/io/serial_cli.c, src/main/mw.c, src/main/sensors/gyro.c, src/main/sensors/gyro.h
New way of gyro soft filtering. Dynamic FIR filter thanks to @digitalentity 
Removed pterm_cut_hz
Added yaw_pterm_cut_hz
Removed 3 point moving average when soft filtering enabled
@hydra 
This is for review, best to merge after gyro sync stuff is merged
At the moment all disabled by default, but we can change defaults for the users to have simillar performance to "betaflight"
=> Gyro Soft LPF Rework // Filter rework

src/test/unit/sonar_unittest.cc
Also fixed error in DECIDEGREES_TO_RADIANS macro. See also:
https://github.com/cleanflight/cleanflight/issues/1599
=> Made testing at max range resilient to floating point rounding errors.

Makefile
Makefile goals corrected, "all" now a bit more meaningfull (i.e. all filetypes, bin and hex) and working.
There was some questions and complaints about Makefile "all" goal on RCG, I had a fix for this on the betaflight fork plus a few other things, refactoring, CC3D variants etc. This PR only handles the make goal issue.
=> Makefile goals corrected.

Makefile, src/main/common/maths.c, src/main/common/maths.h, src/main/flight/imu.c, src/main/flight/lowpass.c, src/main/flight/navigation.c, src/test/Makefile, src/test/unit/flight_imu_unittest.cc, src/test/unit/maths_unittest.cc
This is a continuation of #1092. 
Now cleanflight does not use any libm trigonometry functions. atan2f is ported over from  here: http://www.dspguru.com/dsp/tricks/fixed-point-atan2-with-self-normalization (also available here https://gist.github.com/volkansalma/2972237).
acosf is taken from Handbook of Mathematical Functions by M. Abramowitz and I.A. Stegun (reference implementation available here http://http.developer.nvidia.com/Cg/acos.html)
Code footprint is 1480 byte smaller:
master branch @ 52fe86e66db4e5f3d51422782b781d2b65db0182
text    data     bss     dec     hex filename
119732     364   12860  132956   2075c ./obj/main/cleanflight_CC3D.elf
fast-trig-improvements @ f3b571179dd639b1a047bad2e8b2f03f991db5a1
text    data     bss     dec     hex filename
118252     364   12856 …
=> Added fast acos/atan2 functions. Added unittests for fast trigonometry

src/main/config/config_unittest.h, src/main/flight/pid.c, src/main/flight/pid.h, src/test/Makefile, src/test/unit/pid_unittest.cc
Tests `pidLuxFloat` and `pidMultiWiiRewrite` with minimal intrusion into `pid.c`. Tests:
* basic operation of PID for roll, pitch, and yaw axes
* that contraints to PID values are applied to avoid very large values of `ITerm` and `DTerm` when `rateError` is very large
Additionally, for `pidLuxFloat`, tests:
* `ITerm` accumulates over multiple calls of  `pid_controller` (ie itegration is acually occuring)
* `DTerm` becomes zero after repeated to `pid_controller` with same `rateError` (ie differential is zero when `rateError` is constant)
* Errors of numeric integration used in `pidLuxFloat` are checked against actual integral (ie using calculus) where `rateError` is a linear function of time.
=> Test code for PIDs

src/main/common/atomic.h
gcc 5 has been out for a while and in now the default ARM cross compiler in e.g. Arch Linux.
The gcc 5 generated assembly code follows expectations (Issue 167).
gcc 5 generated firmware has been flight tested in both acrobatic modes (latest betaflight) and navigations modes (with soft serial telemetry, inav-scheduler and inav-gps-rewrite branches).
There is no longer any reason to issue a warning in atomic.h
=> updated atomic.h for gcc 5

src/main/target/RMDO/target.h
Enable G-Tune for the RMRC Dodo target as done for the NAZE recently.
=> Enabled G-Tune for RMRC Dodo target

src/main/common/filter.c, src/main/common/filter.h, src/main/sensors/gyro.c
@digitalentity 
Since gyro sync got merged. What do you think of this? It's for those who like faster looptimes with higher gyro refresh rates.
Maybe some more tables to put in there?
The 2khz filter coeffiecients work well. The HIGH filter may not be enough, but we may consider removing 3 level filtering and stick to 2 level filtering.
=> Expand FIR coefficients for faster looptimes

src/main/target/CJMCU/target.h
This patch just enable magnetometer which was disabled (by error ?) for CJMCU board during merge of G-Tune branch to the master.
=> Enabling magnetometer/compass back in CJMCU target

docs/Rx.md
Updated Rx.md documentation for PPM/CPPM enabled receivers:
* FrSky X4R/X4RSB in CPPM mode
* FrSky S.Bus enabled devices via converter cable
* FlySky iA6B receiver
* Link formatting
=> Updated Rx.md documentation for PPM/CPPM enabled receivers

src/main/drivers/system.c, src/main/target/CHEBUZZF3/target.h, src/main/target/NAZE32PRO/target.h, src/main/target/STM32F3DISCOVERY/target.h
Applied IPU mode where possible.
This is to prevent floating TX lines on startup.
Should cover the period before the device is initialized for first use.
Blackbox was suffering from this and produced a lot of garbage files,
while the LEDs blinked erratically (before first arm/disarm cycle).
OSD's and other serial devices may be affected too.
Tested on Naze and Sparky boards.
=> System - Preset TX of all USARTS on init

Makefile
Recursively invoke `make` with TARGET set correctly.
It is possible to specify multiple targets on make command line.
Special goal `all_targets` will make all known TARGETs.
TARGET-specific goals are passed correctly.
```
make SPARKY NAZE
make all_targets binary test
make all_targets clean
```
=> Add support for TARGET as makefile goal

src/main/config/config.c, src/main/config/config_unittest.h, src/main/flight/pid.c, src/main/flight/pid.h, src/main/io/serial_cli.c, src/test/unit/pid_unittest.cc
Error from measurement is much smoother and preferably better default choices. It also makes rc_smoothing not necessary.
This time user can decide what to use. Configurable parameter for all pid controllers
http://brettbeauregard.com/blog/2011/04/improving-the-beginner%E2%80%99s-pid-derivative-kick/
=> Configurable Delta Approach / rc_smoothing substitute

docs/Battery.md, src/main/sensors/battery.c
- truncate negative amperage values when calculating drawn battery
capacity
- documentation: clarify side effects of the multiwii current meter
output
=> Negative amperage CURRENT_METER fix

src/main/target/LUX_RACE/target.h
Re-add some lines that were removed going from the Colibri to the Lux target in #1775 which made it unable to connect over USB, this fixes the issue while not re-introducing the problem with Serial always showing up on UART2.
=> Fix broken Lux target

src/main/config/config.c, src/main/flight/mixer.c, src/main/flight/mixer.h, src/main/io/serial_cli.c
Saturation handling can now be configured in percentage.
Default setting of 50% should be able to prevent quad trying to correct too hard in crashes, but still be able to have smooth transitions in flight.
=> Configurable saturation handling in airmode

src/main/rx/rx.c, src/main/rx/rx.h, src/test/unit/rc_controls_unittest.cc
Fixes issue https://github.com/cleanflight/cleanflight/issues/1826
Saves 8 bytes of ROM.
=> Removed unused auxChannelCount from rxRuntimeConfig_t.

src/main/config/config.c, src/test/Makefile, src/test/unit/config_unittest.cc
Removed code that set values to zero when they had already been zeroed by `memset`. Each item removed has a line of test code that checks that it has indeed been zeroed by `resetConf`.
Saves differing amounts of ROM depending on build `#defines` for build target. About 50 bytes for CC3D. 184 bytes for ALIENWIIF1.
Fixes issue https://github.com/cleanflight/cleanflight/issues/1825
=> Removed code in resetConf that zeroed already-zero items. Added test code to check.

src/main/drivers/pwm_mapping.c, src/main/target/SPRACINGF3MINI/target.h
@Dominic : this is a desesperate tentative to enable oneshot and PPM on my SPF3Mini. I've reproduced what you did for CC3D WITHOUT UNDERSTANDING clearly what I was doing. I can empiricaly see that it seem to work fine with this fix, but again, I do not understand the impact of this change.
This should fix : #1839 and #1814
=> SPF3Mini : Fix oneshot kills RX_PPM and MAG orientation

src/main/drivers/serial_uart_stm32f10x.c, src/main/drivers/serial_uart_stm32f30x.c
fix typo introduced by copy&paste for F1 (UART5_APB2_PERIPHERALS_TX/RX) and F3 (UART5_AHB_PERIPHERALS_TX/RX) targets
=> fix typo in serial code (was UART5_..._PERIPHERALS_TX instead of RX)

src/main/flight/pid.c
Fixes issue https://github.com/cleanflight/cleanflight/issues/1862.
Also fixes double-negative anti-pattern in checking of `ANGLE_MODE`.
ie anti-pattern
```
if (!condition)
doWhenFalse;
else
doWhenTrue;
```
replaced by
```
if (condition)
doWhenTrue;
else
doWhenFalse;
```
=> Consolidated separate checking of dterm_cut_hz

Makefile
Some simple typo and string clean-ups to the `make help` feature.
Output now prints cleanly as:
```
$ make help
Makefile for the cleanflight firmware
Usage:
make [goal] [TARGET=<target>] [OPTIONS="<options>"]
Valid TARGET values are: ALIENWIIF1 ALIENWIIF3 CC3D CHEBUZZF3 CJMCU COLIBRI_RACE LUX_RACE EUSTM32F103RC MOTOLAB NAZE NAZE32PRO OLIMEXINO PORT103R RMDO SPARKY SPRACINGF3 SPRACINGF3MINI STM32F3DISCOVERY 
Default make goal:
hex         : Make filetype hex only
Optional make goals:
all         : Make all filetypes, binary and hex
binary      : Make binary filetype
hex         : Make hex filetype
all_targets : Make all TARGETs
clean       : clean up all temporary / machine-generated files
flash       : flash firmware (.hex) onto flight controller
st-flash    : flash firmware (.bin) onto …
```
=> Fix Makefile 'make help' feature

src/main/io/serial_msp.c, src/main/io/serial_msp.h, src/test/unit/serial_msp_unittest.cc
Fixes issue https://github.com/cleanflight/cleanflight/issues/1901.
Added test code to check message length of all MSP out messages.
Corrected comments for MSP_TRANSPONDER_CONFIG and MSP_SET_TRANSPONDER_CONFIG as revealed by test code.
=> Corrected MSP_STATUS_EX length. Fixes issue 1901

src/main/config/config.c, src/main/config/config_eeprom.c, src/main/config/parameter_group.c, src/main/config/parameter_group.h, src/main/io/serial_msp.c
Spare bits in the `pgRegistry_t` `pgn` and `size` fields have been used to store the old `flags` and `version` fields.
=> Changes to reduce ROM footprint of parameter groups.

src/main/config/config.c
Not that bad, 248bytes saved:
```
129160	   1236	  19176	 149572	  24844	./obj/main/cleanflight_SPRACINGF3MINI.elf
128912	   1236	  19176	 149324	  2474c	./obj/main/cleanflight_SPRACINGF3MINI.elf
```
=> Use constant initializers in config reset

src/main/config/config.c, src/main/config/config_reset.h
Improved memory - rxConfig_t contains failsafe_channel_configurations and channelRanges thet were allocated in RESET_CONFIG
=> Configuration storage

src/main/build_config.h, src/main/config/config_unittest.h, src/main/main.c, src/main/scheduler.c, src/main/scheduler.h, src/main/scheduler_tasks.c, src/test/unit/scheduler_unittest.cc
Scheduler optimized by using a priority queue. Underlying scheduling algorithm is unchanged.
Two main optimizations:
1. Removed task `isEnabled` flag. Instead task is enabled if it is in the queue, disabled if it is not. This means the main loop only iterates over the enabled tasks, instead of all tasks checking each if it is enabled
2. Tasks are placed in the queue in priority order. This makes the iteration over the queue more efficient.
Added test code for priority queue.
Flight tested on CC3D, CJMCU and SciSky flight controllers (that's all I have).
See also the discussion in issue https://github.com/cleanflight/cleanflight/issues/1692
=> Scheduler optimized by using priority queue

src/main/config/config.c
Assignment to `customMotorMixer` for ALIENWII tidied.
Used enum rather than integer for setting ALIENWII `serialrx_provider`.
One white space tidy.
=> Config cleanup - tidied assignment to customMotorMixer for ALIENWII.

src/main/sensors/sonar.c, src/main/target/CC3D/target.h, src/main/target/EUSTM32F103RC/target.h, src/main/target/NAZE/target.h, src/main/target/OLIMEXINO/target.h, src/main/target/PORT103R/target.h, src/main/target/RMDO/target.h, src/main/target/SPARKY/target.h, src/main/target/SPRACINGF3/target.h, src/main/target/SPRACINGF3MINI/target.h
Sonar pin assignments are now in the relevant `target.h` files. This means it is possible to add SONAR to a target without having to edit the `sensors/sonar.c` file.
This fixes issue https://github.com/cleanflight/cleanflight/issues/1860
I have done a diff of the preprocessor output file `obj/main/<target>/sensors/sonar.i` for all targets. The pin assignments haven't changed, so this is a safe change (there was some whitespace and other minor changes in the `sonar.i` files, though).
=> Moved sonar pin assigmnents out of sonar.c into relevant target.h files.

src/main/flight/altitudehold.c, src/test/Makefile, src/test/unit/altitude_hold_unittest.cc
Fix issue #1837: avoid mixing up rcData and rcCommand when calculating Alt Hold throttle value. This often causes a slight jump or drop when Alt Mode is activated.
=> Fix issue #1837 - alt hold jump when enabling.

src/main/main.c, src/main/sensors/sonar.c
Simplifies call to `sonarGetHardwareConfiguration` by just passing `currentMeterType` since that is all that is used.
=> Simplifies call to sonarGetHardwareConfiguration

src/main/io/serial_4way.c, src/main/io/serial_4way.h, src/main/io/serial_4way_avrootloader.c, src/main/io/serial_4way_avrootloader.h, src/main/io/serial_4way_stk500v2.c, src/main/io/serial_4way_stk500v2.h, src/main/io/serial_msp.c
Here is my attempt to cleanup 4WAY-IF.. It is untested yet (but it should not change anything important), I'll do some test soon.
All comments are welcome
Cleaning 4-way interface sources.
Source formatting changed to CleanFlight style
Removed AVR idioms where possible
Remove some unnecessary optimization
Use serialPort_t instead of mspPort_t
=> Cleanup 4way interface

Makefile, docs/development/Development.md, src/test/Makefile
Updates in Makefiles for Junit xml unit test results and test coverage instrumentation (gcov). Also some help texts. Junit xml results are on it's own make target "junittest", keeping the old target "test" the same as before. 
gcov instrumentation is however hardcoded, not an option. Should not affect compatibilty with other build- or test-scripts. No postprocessing or report generation of test coverage data is included as it might require installation of reporting tools like "gcovr" ( https://github.com/gcovr/gcovr/tree/dev ).
Postprocessing is instead done as a separate job step outside the Makefiles. 
Usage:
make clean
make junittest
/home/andho/projects/coverage/gcovr/scripts/gcovr obj/test --root=src/main -x > coverage.xml
=> Updates for Junit xml unit test results and test coverage. 

src/main/flight/mixer.c
Added motor configuration ASCII diagrams. Aligned mixer array values and comments. Reordered motorMixer_t arrays to group by type, but kept mixer_t order, since this is accessed by array position.
=> Fix for issue #1561 - improved mixer Atail4 values. 

Makefile, src/main/blackbox/blackbox.c, src/main/build_config.c, src/main/config/config.c, src/main/flight/mixer.c, src/main/flight/mixer.h, src/main/flight/servos.c, src/main/flight/servos.h, src/main/io/msp.c, src/main/io/serial_cli.c, src/main/main.c, src/main/mw.c, src/test/Makefile, src/test/unit/config_eeprom_unittest.cc, src/test/unit/flight_mixer_unittest.cc, src/test/unit/msp_unittest.cc
This splits `mixer.c` into two files `mixer.c` and `servos.c`.
`mixer.c` contained a large number of `#ifdef USE_SERVOS` which made it difficult to understand and maintain. This PR fixes that.
=> Split mixer.c into mixer.c and servos.c

src/main/blackbox/blackbox.c, src/main/drivers/accgyro.h, src/main/drivers/accgyro_adxl345.c, src/main/drivers/accgyro_bma280.c, src/main/drivers/accgyro_lsm303dlhc.c, src/main/drivers/accgyro_mma845x.c, src/main/drivers/accgyro_mpu6050.c, src/main/drivers/accgyro_mpu6500.c, src/main/drivers/accgyro_mpu6500.h, src/main/drivers/accgyro_spi_mpu6000.c, src/main/drivers/accgyro_spi_mpu6500.c, src/main/drivers/sensor.h, src/main/flight/imu.c, src/main/io/msp.c, src/main/sensors/acceleration.c, src/main/sensors/acceleration.h, src/main/sensors/initialisation.c, src/main/telemetry/frsky.c, src/test/unit/flight_imu_unittest.cc
This fixes the horrible condition whereby the acc device drivers use an `extern` (`acc_1G`) owned by `sensors/acceleration.c`, i.e. the acc device drivers have a dependency on higher level code.
As @ledvinap has suggested, in the long term it is probably best that the scaling of the acc output is done in the device drivers themselves.
Has the not insignificant side benefit of saving 136 bytes of ROM.
=> Cleanup of acc device drivers extern usage

src/main/drivers/gyro_sync.c, src/main/drivers/gyro_sync.h, src/main/io/serial_cli.c, src/main/main.c, src/main/sensors/gyro.c, src/main/sensors/gyro.h
Make variables and functions static where appropriate. Removed duplicated condition. Made `gyro_soft_lpf` `uint16_t` rather than `float`.
Saves 160 bytes of ROM.
=> Cleanup of gyro_sync.c

src/main/io/msp_protocol.h, src/main/io/serial_msp.c
Related to CF cfg issue 153
Requires the corresponding patch in cleanflight-configurator
=> MSP: do not scale mag_declination value by 10

docs/Board - SPRacingF3Mini.md, src/main/drivers/pwm_mapping.c
Via MOTOR 6-8 for RC CH 1-4 and PPM for AUX1.
PA0-3 are the input which are __NOT 5V TOLERANT__.
This works perfectly with receivers that give 3v outputs, such as the nice little FrSky VD5M (Tested).
=> SPRACINGF3MINI - Add 5 channel parallel PWM receiver support

src/main/flight/pid.c, src/main/flight/pid.h, src/main/flight/pid_luxfloat.c, src/main/flight/pid_mwrewrite.c, src/main/mw.c, src/main/sensors/acceleration.h, src/test/unit/flight_pid_unittest.cc
Fixes issue https://github.com/cleanflight/cleanflight/issues/2177
=> Fix for DTerm scaling in pid_luxfloat to match pid_mwrewrite.

src/main/drivers/compass_ak8963.c, src/main/flight/pid_luxfloat.c, src/main/flight/pid_mwrewrite.c, src/main/io/ledstrip.c, src/main/mavlink/mavlink_types.h
Trivial fix for warnings in current code.
mavlink fix should be probably reverted when some conclusion about -Wpedantic is reached.
@hydra : Please merge this ASAP - it is so annoying to skip existing warnings when testing new code ..
=> Fix warnings

lib/main/STM32_USB-FS-Device_Driver/inc/usb_regs.h
looks like gcc bug - gcc generates half-word access in _SetEPTxAddr / _SetEPRxAddr macro. Using `addr & ~ 3` fixes this and VCP works fine
Code works when optimization level is decreased for `Virtual_Com_Port_Reset`
here is invalid code for reference:
```
.loc 4 493 0
ldr	r3, [r7]	@ D.5186, MEM[(volatile unsigned int *)1073765456B(BTABLE)] SetEPRxAddr
uxtah	r3, r2, r3	@ D.5188, tmp245, D.5186
lsls	r3, r3, #1	@ D.5189, D.5188,
mov	r9, #64	@ tmp249,
ldrh	r2, [r3]	@, *_219
strh	r9, [r3]	@ movhi	@ tmp249, *_219
ldrh	r2, [r3, #2]	@, *_219
strh	r4, [r3, #2]	@ movhi	@ tmp217, *_219
.LVL58:
.LBE93:
.LBE98:
.LBB99:
.LBB100:
.loc 4 481 0
ldr	r3, [r7]	@ D.5186, MEM[(volatile unsigned int *)1073765456B(BTABLE)] SetEPTxAddr
uxth	r3, r3	@ D.5187, D.5186
add	r3, r3, #536870912	@ D.5188, D.5187,
add	r3, …
```
=> USB-VCP gcc 5.3  fix

src/main/io/msp.c, src/main/io/msp_protocol.h, src/test/unit/msp_unittest.cc
Implement new MSP messages :
- MSP_LED_STRIP_MODECOLOR
- MSP_SET_LED_STRIP_MODECOLOR
Additionally, in MSP_SET_LED_COLORS, check color HSV validity before appplying it.
Based on @ledvinap's Ledstrip Cleanup.
=> Implement LEDStripModeColor messages in MSP

src/main/common/utils.h
memcpy was not mangled on win32 targets
=> Fix win32 unitests

docs/Controls.md, docs/Getting Started.md, src/main/io/beeper.c, src/main/io/statusindicator.c, src/main/io/statusindicator.h, src/main/mw.c
Use Warning LED flash count to inform arming prevention reason.
| Reason for disabled Arming               | LED Flashes |
|------------------------------------------|-------------|
| CLI is active in the configurator        | 2           |
| Failsafe mode is active                  | 3           |
| The aircraft has landed in failsafe mode | 3           |
| Maximum arming angle is exceeded         | 4           |
| Calibration is active                    | 5           |
| The system is overloaded                 | 6           |
See PR  #2182
Implements @ledvinap's travis fix.
Looking forward to read your comments.
=> Status led pattern: disabled arm reason

docs/Serial.md
Fix a typo in the doc buad => baud
=> Fix a typo

src/main/drivers/light_led.h, src/main/drivers/light_led_stm32f10x.c, src/main/drivers/light_led_stm32f30x.c
Is this unintentional mistype or there is some logic behind it?
I think it's more appropriate to declare it as "extern" in header.
=> cleanup led_config declaration.

src/main/common/atomic.h
This one is just disables all ARM-specific macro functions for non-arm targets (like x86).
=> Disable arm atomic functions on non-arm devices

src/main/common/filter.c, src/main/common/filter.h, src/main/config/config_unittest.h, src/main/fc/cleanflight_fc.c, src/main/flight/imu.c, src/main/flight/pid.c, src/main/flight/pid.h, src/main/flight/pid_luxfloat.c, src/main/flight/pid_mw23.c, src/main/flight/pid_mwrewrite.c, src/main/io/serial_cli.c, src/main/sensors/gyro.c, src/test/unit/flight_pid_unittest.cc
This addresses issue  "Use PT1 filters rather than biQuad filters for PIDs. Improve filter defaults" from issue https://github.com/cleanflight/cleanflight/issues/2213.
=> Merge PID filter changes from betaflight.

src/main/io/serial.c
Small, irrelevant (caz softserials comes in a pair) mistake here.
=> Fix a typo in openSerialPort()

src/main/fc/msp_server_fc.c
This change was added in cleanflight and then got left behind in a cleanup.
This brings an incompatiblity with the configurator.
Possibly fixes  #2290
=> don't scale mag_declination by 10 (readd)

docs/Board - CC3D.md
Only single binary image mode can be used since version 1.11.0
=> Update flashing procedure for CC3D

src/main/common/filter.c, src/test/unit/rx_rx_unittest.cc
The 2nd parameter is passed as an 'int', but the function fills the block
of memory using the 'unsigned char' conversion of this value.
"void* memset( void* dest, int ch, std::size_t count );
Converts the value ch to unsigned char and copies it into each of the first
count characters of the object pointed to by dest."
=> The 2nd memset() argument '1500' doesn't fit into an 'unsigned char'.

src/main/sensors/initialisation.c
The current code tests for an MS5611 baro and then a BMP085 baro.   
The test for an MS5611 relies on a 4 bit CRC which, on occasion, the BMP180 will pass (the BMP180 is a drop in replacement for the BMP085).  So the FC thinks it has an MS5611 connected.
This PR tests for a BMP085 (BMP180) before testing for an MS5611.
Another approach would be to test for an MS5611 first, and if the CRC is correct, check an undocumented address = 0x00.  That may work today but is a risky approach and could cause issues in the future.  Plus, it's extra code.
=> Sensors - Detect BMP085 before MS5611

docs/development/Building in Ubuntu.md
There are a few other pull requests out to fix the version numbers of the packages, but none addressed the issue that the repository url listed in the docs is now redacted.
=> Docs: Ubuntu - Updating the Repo Url Because the old Url is dead.

src/main/telemetry/smartport.c
Fixes a bug introduced by commit 2507b90a2827496fd9aae04624bc2a8aabbb64f3 that produces incorrect flight mode data on SPort telemetry.
Also included a change to produce expected output if GTUNE_MODE and PASSTHROUGH_MODE are set together.
=> Fixed SPort telemetry flight mode flag bug

src/main/flight/pid.c, src/main/flight/pid.h, src/main/flight/pid_luxfloat.c, src/main/flight/pid_mwrewrite.c, src/main/io/serial_cli.c
This is an updated version of PR #2268 "Add horizon_incl_fact parameter"
This modification adds two new CLI commands, 'horizon_tilt_effect' and 'horizon_tilt_mode', which control the effect the current inclination has on self-leveling in the Horizon flight mode.  With the existing horizon mode, the strength of the self-leveling is solely dependent on the stick position.  This is problematic when trying to do maneuvers like large loops and fast-forward flight.  Adding a factor that takes into account the current inclination of the craft provides a big improvement for these maneuvers and improves the "feel" of horizon mode.  (The current inclination is the number of degrees of pitch or roll that the vehicle is away from level, whichever is greater).
These commands affect Horizon mode for …
=> Add horizon_tilt_effect command

src/main/drivers/bus_i2c_stm32f10x.c
On F1 targets, `i2cErrorCount` is never counted up.
On F1 targets, errors are detected and handled silently by `i2c_er_handler()`, never by soft timeouts. Should honor the value of `error` variable set by `i2c_er_handler()` when checking for errors.
=> Fix i2cErrorCount ignorance on F1 targets

src/main/config/config_eeprom.c, src/main/config/config_eeprom.h, src/main/config/parameter_group.c, src/main/config/parameter_group.h, src/main/fc/config.c, src/main/osd/config.c
All parameter groups  initialized, either from EEPROM or reset to
default.
Stored record version is checked, mismatched version is ignored
=> Redesign PG loading from EEPROM

src/main/config/config_eeprom.c
Invalid length was passed to pgLoad, overwriting PG data when record
size was increased
=> Fix invalid length of EEPROM record

Makefile, src/main/target/RMDO/target.h
Tested this on RMRC Dodo board with HolyBro M8N GPS (HMC5983L part on I2C).
=> Add HMC5883 compass support to RMDO target

docs/Rx.md
I am researching which Spektrum Rx I can use with Vortex 250 Pro and noticed that one of the links is outdated.
=> Fix broken link to Spektrum Rx

src/main/fc/boot.c, src/main/flight/imu.c, src/main/flight/imu.h, src/main/sensors/acceleration.c, src/main/sensors/acceleration.h, src/test/unit/flight_imu_unittest.cc, src/test/unit/msp_fc_unittest.cc
Filtering is now done in acceleration.c, using the biquad filter, like in betaflight. Changed imu and boot.c accordingly. Fixed issues with unit-test flight_imu_* and msp_fc_* due to changes in accelerometer filtering. This is the same a PR #2505, but this time under a proper branch name, since i messed it up the first time.
Test flight in horizon and angle mode was OK for me, although i could do only limited testing.
=> Changed code for accelerometer handling

docs/development/Atomic Barrier.md, src/main/build/atomic.h
`=m` output operand means that value is write only, gcc may discard previous value because it assumes that it will be overwritten. This bug was not triggered in gcc v4 because `asm volatile` triggered full memory barrier.
With old version, this code will increase `markme` only by 2, not 3:
```
static int markme = 0;
markme++;
ATOMIC_BLOCK_NB(0xff) {
ATOMIC_BARRIER(markme);  // markme is marked as overwritten, previous increment can be discarded
markme++;
}
markme++;
```
=> Fix atomic.h

src/main/osd/fc_state.h, src/main/osd/msp_client_osd.c, src/main/osd/osd.c, src/main/osd/osd_element.c, src/main/osd/osd_element.h, src/main/osd/osd_element_render.c, src/main/osd/osd_element_render.h, src/test/unit/osd_screen_unittest.cc
This is my first Cleanflight PR that adds a new feature, so please feel free to comment and let me know if I did anything wrong. I have included a unit test, let me know if I should expand it. Thanks.
I have tested this on my OSD board, in combination with my SP Racing F3 Evo running Betaflight 3.1 (today's master) - https://www.youtube.com/watch?v=jtsUIIeRwjQ
See #2399
If everything checks out, I will try to add other OSD elements as well in separate PRs, if that's OK.
=> OSD - Add the averageSystemLoadPercent OSD element

.travis.yml, Makefile, README.md
Merged some stuff from https://github.com/mkschreder/ninjaflight after reading the issue https://github.com/cleanflight/cleanflight/issues/2476
This pull request adds coverage reports as a list in the build output if lcov tool is installed 
It also publishes data to the server at https://coveralls.io which is free for open source projects.
(Example page from my account: https://coveralls.io/jobs/19911189)
Credits are due to @mkschreder
Stuff to do by the maintainer when merging:
- Create account at coveralls.io and enable the cleanflight repository (it takes like five seconds)
- Update the link for the status gadget in the end of README.md (https://github.com/unitware/cleanflight/blob/lcov-coverage-report/README.md)
=> Lcov coverage report

src/main/osd/fc_state.h, src/main/osd/msp_client_osd.c, src/main/osd/osd.c, src/main/osd/osd_element.c, src/main/osd/osd_element.h, src/main/osd/osd_element_render.c, src/main/osd/osd_element_render.h, src/test/unit/osd_screen_unittest.cc
The FC baro/sonar value in cm is converted to a value in meters.
I have tested this with a stationary quad (with the Evo FC running BF 3.1. with the baro enabled) but haven't done a real test flight yet.
=> OSD - Add the baro altitude OSD element, with a unit test.

src/test/Makefile, src/test/unit/rx_ibus_unittest.cc
Comments and questions: 
- I'd expect that runtime configuration was not initialized unless there was a serial port to run but the implementation states otherwise (ibus.c:62)
- ibusInit: is it ok to have undefined channel values after init? (ibus.h:75)
- ibusFrameStatus should return rxFrameState_t not uint8_t
=> added unit tests for ibus serial rx

docs/Blackbox.md, src/main/drivers/flash_m25p16.c
This is to add support for another 8MB SPI flash chip, Macronix MX25L64. It's another option for people who want to mod and expand their CF onboard memory for use with Blackbox. Tested on a CC3D. Attached is a picture of the mod and a sample log file recorded with the chip and patch. The log has only some stick movement, no flying.
[blackbox_log_2016-01-29_232216_8MB.TXT](https://github.com/cleanflight/cleanflight/files/110644/blackbox_log_2016-01-29_232216_8MB.TXT)
=> Add support for 64Mbit (8MB) SPI flash chip Macronix MX25L64.

src/main/drivers/bus_i2c_stm32f10x.c, src/main/drivers/dma.c, src/main/drivers/exti.c, src/main/drivers/irq.h, src/main/drivers/serial_uart_stm32f10x.c, src/main/drivers/serial_uart_stm32f30x.c, src/main/drivers/timer.c
IRQHANDLER(name)
Check that `name` is valid handler name (corresponding IRQ number is defined) and emit handler definition
`IRQHANDLER(TIM1_UP_IRQ)` will expand to `void TIM1_UP_IRQHandler(void)` on F1, but generate compile-time error on F3 target (correct name is TIM1_UP_TIM16_IRQ)
=> Feature irqhandlers

src/main/drivers/accgyro_mpu6500.h
was broken by 196baa4e8715de8edd0ef0a8f0bd8c4d34ebf828.
The bit to enable bypass mode was incorrect.
@blckmn @borisbstyle you'll probably want to pull this into betaflight to close https://github.com/betaflight/betaflight/issues/2555
=> CF/BF - Fix AK8975 mag detection

src/main/target/SPRACINGF3EVO/target.h
…the serial port count was mismatched and causing duplicate serial ports to appear in the configurator.
=> CF/BF - SPRACINGF3EVO - remove the two #undefs to enable softserial

src/main/drivers/accgyro_mpu6500.h
as per comments by @martinbudden  on https://github.com/betaflight/betaflight/pull/2556#pullrequestreview-25139441
=> CF/BF - Further MPU9250/AK8975 mag cleanup.

src/main/fc/rc_controls.c
this resulted in no yaw from RC input.
=> fix missing yaw default when using PGs.

src/main/target/SPRACINGF3NEO/target.c
Allow LED and transponder even when DSHOT is compiled.
Enabling LED_STRIP and/or TRANSPONDER will break DSHOT on motor outputs
1 and 3.
Without DSHOT, LED_STRIP and TRANSPONDER work fine, at the same time.
=> CF/BF - SPRACINGF3NEO - Fix incorrect LED strip output pin.

src/main/target/COLIBRI_RACE/i2c_bst.c
Based on updated requirements from TBS engineers.
Larry Ho: "
BST_MAG_CALIBRATION,
BST_ACC_CALIBRATION,
BST_SET_PID,
BST_SET_RC_TUNING,
BST_SET_LOOP_TIME,
BST_SELECT_SETTING,
BST_SET_RX_MAP,
BST_SET_MISC,
BST_SET_DEADBAND,
BST_SET_FC_FILTERS,
BST_SET_FEATURE,
BST_SET_RX_CONFIG,
BST_SET_MODE_RANGE,
BST_SET_LED_COLORS,
BST_SET_LED_STRIP_CONFIG,
BST_EEPROM_WRITE,
BST_REBOOT,
BST_DISARM,
BST_ENABLE_ARM,
BST_PID,
BST_STATUS,
BST_RC_TUNING,
BST_LOOP_TIME,
BST_RX_MAP,
BST_MISC,
BST_DEADBAND,
BST_FC_FILTERS,
BST_FEATURE,
BST_RX_CONFIG,
BST_LED_COLORS,
BST_LED_STRIP_CONFIG,
BST_API_VERSION"
There was a required to keep `BST_BF_BUILD_INFO`, which is not on the
list above, but has been deprecated for ages.  Since it was never used
we will keep the replacement `BS_BUILD_INFO` instead.
Dominic …
=> CF/BF - Restore BST_API_VERSION and BST_BUILD_INFO

docs/Customized Version.md
According to the issue https://github.com/cleanflight/cleanflight/issues/2654 I've created a little document explaining how to compile your own version of CleanFlight, especially useful in the latest version 2.x that has disabled a lot of features that worked in version 1.x. 
This document explains how to disable and enable some features in the code. In this way you can, for example, have magnetometer or GPS in a NAZE32 flight controller.
This document is aimed to people with some programming skill, maybe in a future the process can be automated to let every user create it's own online customized version.
I'm not english native, so it needs a good revision.
I've put it in the `docs` folder, I don't know if it will be better in the `docs/development`. I can change it if it's necessary. …
=> Document customized version

src/main/drivers/timer_def.h, src/main/target/CC3D/target.c, src/main/target/CJMCU/target.c, src/main/target/COLIBRI_RACE/target.c, src/main/target/FURYF7/target.c, src/main/target/LUX_RACE/target.c, src/main/target/MICROSCISKY/target.c, src/main/target/NUCLEOF7/target.c, src/main/target/OMNIBUS/target.c, src/main/target/STM32F3DISCOVERY/target.c
This PR solves https://github.com/cleanflight/cleanflight/issues/2674
Thanks to @ledvinap for the code to make the `DEF_TIM` accept variable args.
Trying to make a customized version of CleanFlight, I found a problem: if I commented the LED_STRIP feature to get some free space, the compiler shows some issues. This PR makes all the targets compile with and without the LED_STRIP feature.
Please, these code needs some review because:
- I've only a NAZE32 board, without leds. So I only can be sure that the code compiles in ALL targets with and without the LED_STRIP feature and it works in the NAZE32. I've not tested it in other boards.
- I've a doubt when the values are NULL. For example, in the FURYF4 (that I've not touch in this PR), appears this code commented:
```{ TIM8,  IO_TAG(PC9), …
```
=> Fix compile issues deactivating led strip

src/main/fc/fc_init.c
This solves https://github.com/cleanflight/cleanflight/issues/2685
When compiling a target with `#undef USE_PWM` the linker fails with this message:
```
Linking NAZE
/tmp/ccCHoCnV.ltrans1.ltrans.o: In function `servoDevInit':
/mnt/d/git/cleanflight-2.x/./src/main/drivers/pwm_output.c:354: undefined reference to `pwmConfig_System'
collect2: error: ld returned 1 exit status
make[1]: *** [obj/main/cleanflight_NAZE.elf] Error 1
make[1]: se sale del directorio «/mnt/d/git/cleanflight-2.x»
make: *** [hex] Error 2
```
This PR solves the problem. Maybe is not the better code, but I didn't wanted to modify the condition. Reviews are welcome.
=> Fix compile linking issues when USE_PWM is disabled

src/main/drivers/compass_ak8963.c, src/main/target/SPRACINGF3EVO/target.h, src/main/target/SPRACINGF3MINI/target.mk
It was broken, again. 😒
I bisected it, found that this commit broke it:
60c2b81#diff-b0765a975ceb7d528b0ce88f63dcda40L112
the changes seemed incorrect and/or unfinished.
I also added the MPU6500_BIT_BYPASS_EN to the MPU9250 configuration - though this is actually being done twice now, once via the MPU6500 code and once in the al8963 spi detection code.
Please can I respectfully request that any future changes to the MPU9250 and AK8963 code are tested on real hardware.
Note that it's not enough to just run your changes without cold booting, you need to also test from a COLD BOOT and a WARM BOOT.
=> Fix spracingf3evo mag detection

src/main/target/NAZE/initialisation.c
The NAZE32_SP can only have one port because it the pins are not
available for use as soft serial.
The NAZE32_SP should only configure the I2C pins if USART3 is not used.
See https://github.com/cleanflight/cleanflight/issues/2668#issuecomment-290953473
=> CF/BF - Fix Naze32 missing second softserial port.

src/main/io/gps.c
This PR solves https://github.com/cleanflight/cleanflight/issues/2698
The GPS is unstable in NAZE32 (customized compilation, as GPS is disabled for F1 targets), but with this little change, based on CleanFlight 1.x, the GPS is stable as rock again. I don't know anything about GPS system, I've only changed lines between 1.x and 2.x until I found the lines that make it work again.
So if someone can take a look at it to see if this change is clean or can have secondary effects will be great. Maybe can be added with `#if defined` only for NAZE or only fo F1 CPUs. I'm open to test any changes.
Regards!
=> Make the GPS stable again

src/main/target/NAZE/target.h, src/main/target/common.h
Disabling LTM allows MAG to be enabled.
Likely more users want MAG support than LTM support on a NAZE32 so this makes sense - seems like a shame to waste the MAG sensors on the NAZE32.
=> CF/BF - Enable MAG on NAZE32.

src/main/fc/cli.c
Noticed the the CLI servo command referenced invalid arguments via magic numbers.  Corrected that.
=> Fixed servo cli to process correct arguments.

src/main/io/displayport_msp.c
...  when OSD over MSP is enabled.
=> CF/BF - Fix CLI being spammed with OSD MSP_DISPLAYPORT messages

src/main/target/NAZE/config.c
This solves https://github.com/cleanflight/cleanflight/issues/2666
@hydra I know you closed it, but I haven't do it before because it was assigned ;-).
The problem are the default values for the NAZE32. It uses serial device by default, but some hardware revisions have an on-board dataflash. This PR detects this revisions and uses by default the on-board dataflash.
=> For NAZE32 REV5 and REV6 use the dataflash for blackbox as default

src/main/target/SPRACINGF3NEO/config.c
to be appropriate for the XSR receiver.
=> CF/BF - SPRACINGF3NEO - Change the default telemetry settings

src/main/fc/cli.c, src/main/fc/settings.c, src/main/target/SPRACINGF3NEO/config.c, src/main/target/SPRACINGF4EVO/config.c, src/main/telemetry/hott.c, src/main/telemetry/smartport.c, src/main/telemetry/telemetry.c, src/main/telemetry/telemetry.h
Two issues:
1 - failure to work on softserial ports.
The TX pin was not allocated due to the initial port mode.
HoTT telemetry is different in that it changes the serial port mode
between sending and receiving.
This change opens the port in RX/TX mode so that both RX and TX pins are
initally allocated.
Test scenario:
* HoTT on SoftSerial 1
* Diode connecting between RX and TX pins.
2 - bidirectional hardware ports were not supported.
Renamed `sport_halfduplex` to `tlm_halfduplex`.  The setting is now used
by sport and hott telemetry.
=> CF/BF - Fix HoTT telemetry.

src/main/common/utils.h, src/main/drivers/timer_def.h
The idea is to use preprocessor magic to simplify actual mapping
definition, so that mapping database is easier to check/upkeep.
=> Simplify timer DMA definition

src/main/fc/cli.c
* Save a few more bytes of flash space by reusing the same format
string.
* Remove magic numbers.
* Reduce function calls.
* Make it show parse error if the length is not correct.
* Avoid modifying the cmdline variable - always use the buffer.
=> CF/BF - Cleanup the map command.

src/main/target/SPRACINGF3/target.h
It appears @borisbstyle broke it with this commit. 907a184
After it was commented out @mikeller later deleted it in ce6d020
See https://github.com/cleanflight/cleanflight/issues/2755
=> CF/BF - SPRACINGF3 - Re-instate SONAR.

Makefile
Adding VARIANT allows better flexibility in the target specific files.
It has always irked me that code for variants appears above official targets.  With this define we can fix this situation and hopefully improve the readability of the target files.  Especially ones were there are significant differences.
=> CF/BF - Add VARIANT define to all variant targets.

src/main/common/streambuf.c, src/main/fc/fc_msp.c, src/main/fc/fc_msp.h, src/main/fc/runtime_config.h, src/main/telemetry/crsf.c
- active boxes use bitmask instead of array
- active box serialization is loop based instead of huge expression
Was included in
https://github.com/cleanflight/cleanflight/pull/2075/commits, but never
ported to BF and eventually lost
=> Improve box serialization

docs/Battery.md, docs/Board - AlienFlight.md, docs/Board - MotoLab.md, docs/Buzzer.md, docs/Display.md, docs/Getting Started.md, docs/development/Hardware Debugging in Eclipse.md, docs/development/Hardware Debugging.md
Markdown links cannot have actual spaces in the filename.  Use URL-encoded
spaces (%20) instead.
robo-fixed using:
sed -i -e 's/\(]([^ )]*\) \([^"]\)/\1%20\2/g' **/*.md
If you don't use zhell, you may need to customize the ** part of that command.
=> Fix markdown links to filenames with spaces

src/main/target/NAZE/target.h
This PR replaces https://github.com/cleanflight/cleanflight/pull/2812. It activates 'USE_RX_MSP' for NAZE targets. I am not able to test this on hardware for now, since commit 839b5dd408737045bcf7f83df015d1496acaa759 breaks cleanflight on NAZE targets.
=> activate 'USE_RX_MSP' on NAZE targets

docs/Rx.md, docs/Telemetry.md
This PR https://github.com/cleanflight/cleanflight/pull/2554 was not merged in CF1.x, and was merged into BF. But in BF the doc was not updated.
This PR only recovers the docs updated in this PR, explaining how to use the same UART for SerialRX and Telemetry in IBus.
=> Documentation for combine ibus serial rx and telemetry on same UART

Makefile
This goes some way to addressing #2808 and certainly allows the new SPRACINGF4NEO target to have all the features enabled now.  See https://github.com/cleanflight/cleanflight/pull/2835
=> CF/BF - Always size optimize some non-speed critical files.

src/main/fc/config.c
When added:
```
#undef USE_SERVOS
```
to the `target.h` file to free some space to other features, the compiler gives an error because:
```
/tmp/ccq2pmk9.ltrans15.ltrans.o: In function `loadEEPROM':
/mnt/d/git/mcgivergim/cleanflight/./src/main/config/config_eeprom.c:180: undefined reference to `servoMixers'
```
This commit solves the problem.
NOTE: I don't know what the code does exactly, so maybe it's better to put the conditional in other part. Please review the code before merge.
=> Fix compiles issues when not defined USE_SERVOS

src/main/io/osd.c
so it aligns with 'craft_name' and battery voltages.
=> CF/BF - Fix alignment of OSD 'disarmed'

src/main/sensors/current.c
I think there is a problem in currentMeterESCReadCombined function, it fills out meter pointer and then calls currentMeterReset function which clears the pointer.
=> Read current from ESC fixed.

src/main/fc/fc_init.c, src/main/flight/servos.c, src/main/flight/servos.h
Prior to this only the first filter was initialised.  The bug was clearly visible from the motors tab in the UI - servos 2-8 were always static.
Either one flag per servo is needed or just initialise all of them after the targetPidLooptime is set.  I went with the latter as it's a) simpler , b) makes the main loop faster, and c) follows the same pattern as other filter initialisation code.
Tested and working here.
=> CF/BF - Fix servo filter initialisation.

src/main/sensors/voltage.h, src/main/target/SPRACINGF4NEO/target.h
The F4 NEO ADC readings fluctuate quite a lot, this fix helps, but at the cost of latency.
The graph above shows the filtered ADC output, the unfiltered output and the difference between the two, for comparison.  Low-noise bench power supply used for tests.
This fix works for now, but perhaps it's working making the ADC frequency configurable?
=> CF/BF - SPRACINGF4NEO stabilise ADC readings.

docs/Battery.md
The formula for changing the current sensor scale based on consumed and replaced battery power is incorrect. It increases the scale value when it should decrease it and vice versa.
This pull request corrects that.
=> Doc update for current sensor 

docs/Battery.md
-Fix incorrect formula in example section of Battery Charger method calibration
-Fix incorrect tense from "mAh draw" to "mAh drawn"
-Simplify instruction steps to be more direct and concise
-Replace abstract example calculation values with rounded numbers to make formula translation more obvious
-Make formula placeholder names match those used in Configurator
-Cross fingers that is it so clear now that not even a grandmother would try to change it again ;)
=> Fix and clarify Virtual Current Sensor docs

docs/USB Flashing.md, docs/development/Building in Ubuntu.md
Updates to the documentation (Building in Ubuntu.md, and USB flashing.md). 
Building in Ubuntu was very outdated. USB flashing did not explain the underlying concepts enough
so a section containing some background information for troubleshooting was added.
=> Leco doc update2

src/main/drivers/display.c, src/main/drivers/display.h, src/main/drivers/max7456.c, src/main/drivers/max7456.h, src/main/io/displayport_max7456.c, src/main/io/displayport_msp.c, src/main/io/displayport_oled.c, src/main/io/displayport_rcdevice.c, src/main/io/displayport_srxl.c, src/main/io/osd_slave.c, src/main/io/rcdevice_osd.c, src/main/io/rcdevice_osd.h
fixes continual screen flickering issue that can sometimes be experienced after powering off/on either the FC or the OSD while the other board is still on.
key points:
1) max7456ReInitIfRequired extracted from max7456DrawScreen
2) max7456ReInitIfRequired now also called by max7456RefreshAll
3) max7456BuffersSynced added
4) displayPort api updated with isSynced
5) OSD slave can now use isSynced to ensured the display is synced because `displayDrawScreen()` may return WITHOUT having fully updated the screen.
6) When OSD slave boots, the logo and text is now displayed after the first call to displayResync(), rather than it being eventually called by a random amount of calls to `displayDrawScreen` via the OSD_SLAVE_TASK.
7) displayPort MSP displayResync now sends the MSP_DISPLAYPORT command, …
=> Improve OSD slave timeout/disconnect/reconnect handling.

src/main/rx/rx.c
Previous logic changes were causing the RX task to run every loop for PWM rx leading to 100% CPU load. Reverted PWM processing to be based on a time interval rather than whether new data is available. With PWM we can't differentiate when new data is available as it's a continuous stream.
=> Fix PWM rx 100% CPU load (#5598) (#5606)

Makefile
Some developers use external tools that require fixed filenames, e.g. `obj/some-file.bin`.
Recently the git commit revision, or `_norevision` is added to the filenames, so they become e.g. `obj/some-file_revision.bin`.  This means that the external tools either fail to find the files, or the tools must also be changed and passed the revision number as an argument, this is infeasible, impractical and sometimes impossible.
The reason that the git commit revision or `_norevision` was added to the filenames was so that users know what commit the firmware is built from, this is especially handy for testers and users giving early feedback of test builds.
This PR keeps both developers and users happy, since now when doing a normal build both sets of files are created.  e.g.  `obj/some-file.bin` …
=> Create variably named files as an additional make step.

src/main/target/SPRACINGF3NEO/target.h
Rev A through C = 1-3, Prototypes Only.
Rev D = 4, Limited distribution. (Gyro on SPI 1, OSD on SPI 3)
Rev E = 5, Retail sales. (Gyro on SPI 3, OSD on SPI 1)
=> Support SPRACINGF3NEO Rev D and later.

make/targets.mk, src/main/platform.h
To build a custom target:
* create YOUR_TARGET.mk file, empty.
* create YOUR_TARGET.h file, empty.
* in YOUR_TARGET.h file, add '#include "target.h"` as required.
* in YOUR_TARGET.h file, `#undef`/`#define` whatever you like.
* Compile with `make TARGET=YOUR_TARGET`.
* Flash the generated `obj\cleanflight_x.x.x_YOUR_TARGET.hex`
e.g.
```
SPRACINGF3NEO_CUSTOM1.h
SPRACINGF3NEO_CUSTOM1.mk
make TARGET=SPRACINGF3NEO_CUSTOM1
```
For a more complete example, see this commit:
https://github.com/hydra/cleanflight/commit/9b16fc0be9152a996fbbd6aa5600173b57f4c6e2
* Handy when the code compiles, but no longer fits in flash due to all the
different hardware support compiled in by default.
* Useful when you need custom binaries, but don't want your changes interfering with the base target files.
=> Provide a way for users to easily create custom target headers.
