cleanflight/cleanflight

docs/Autotune.md
So that people don't try it and get disappointed :).
=> Docs: note that autotune doesn't support pid_controller 2

docs/Board - CJMCU.md
Clarified how to identify the difference between CJMCU revisions.
=> Add clarification of revisions to CJMCU Docs

docs/Board - Sparky.md
Instructions on how to flash sparky in DFU mode with Windows based on the video instructions by Thomas Shue.
(this is my first pull ever, do let me know what I did wrong and what needs to be improved :-) !)
Thanks !
=> Documentation update: Added Windows USB flash instructions (DFU) to Board - Sparky.md

docs/development/Building in Windows.md
=> Update Building in Windows.md

src/main/common/maths.c, src/main/common/maths.h, src/main/config/config.c, src/main/drivers/accgyro_spi_mpu6000.c, src/main/drivers/accgyro_spi_mpu6500.c, src/main/flight/flight.h, src/main/flight/imu.c, src/main/flight/imu.h, src/main/flight/navigation.c, src/main/main.c, src/test/Makefile, src/test/unit/flight_imu_unittest.cc
Review this request first: #405, then only compare new changes onto that one, or ask me to rebase :)
Added clarifying comment to the throttle correction function in imu.h.
=> Throttle correction comment

src/main/common/maths.h, src/main/flight/imu.c
Review this request first: https://github.com/cleanflight/cleanflight/pull/398, then only compare new changes onto that one, or ask me to rebase :)
Removing last reference to RAD constant. (decopling)
=> Switch from RAD constant to degreesToRadian function.

src/main/common/maths.h, src/main/drivers/accgyro_spi_mpu6000.c, src/main/drivers/accgyro_spi_mpu6500.c, src/main/flight/imu.c, src/main/flight/navigation.c
Review this request first: https://github.com/cleanflight/cleanflight/pull/398, then only compare new changes onto that one, or ask me to rebase :)
Switched from trying to redefine M_PI to be a float instead of double, to rather explicitly using M_PIf.
=> Explicit floating point pi

src/main/common/maths.h, src/main/drivers/accgyro_spi_mpu6000.c, src/main/drivers/accgyro_spi_mpu6500.c, src/main/flight/imu.c, src/main/flight/navigation.c
Review this request first: #400, then only compare new changes onto that one, or ask me to rebase :)
Changed the comments around the vector rotate function.
=> Vector rotate method commits

src/main/common/maths.h, src/main/drivers/accgyro_spi_mpu6000.c, src/main/drivers/accgyro_spi_mpu6500.c, src/main/flight/imu.c, src/main/flight/navigation.c
Review this request first: #401 , then only compare new changes onto that one, or ask me to rebase :)
Added explanatory comment to the calculateHeading method.
=> Calculate heading comments

src/main/common/maths.h, src/main/drivers/accgyro_spi_mpu6000.c, src/main/drivers/accgyro_spi_mpu6500.c, src/main/flight/imu.c, src/main/flight/navigation.c, src/test/Makefile, src/test/unit/flight_imu_unittest.cc
Review this request first: #402, then only compare new changes onto that one, or ask me to rebase :)
Fixed the flight_imu_test after including maths.h from it :)
=> Flight imu test maths

src/main/common/maths.c, src/main/common/maths.h, src/main/config/config.c, src/main/drivers/accgyro_spi_mpu6000.c, src/main/drivers/accgyro_spi_mpu6500.c, src/main/flight/flight.h, src/main/flight/imu.c, src/main/flight/imu.h, src/main/flight/navigation.c, src/main/main.c, src/test/Makefile, src/test/unit/flight_imu_unittest.cc
Review this request first: #404, then only compare new changes onto that one, or ask me to rebase :)
Moved vector code from imu into maths.h
=> Move math to math module

docs/PID tuning.md
Should fix issue #359, the controller documentation is largely written by QuadBert.
=> Add PID and PID controller documentation

docs/LedStrip.md, src/main/io/ledstrip.c, src/main/io/ledstrip.h, src/main/io/serial_msp.c
I've added the led on/off switch mode, with a flag to lower the overhead and all controlled by the LEDLOW mode.
C
=> Led on off

src/main/blackbox/blackbox.c, src/main/common/maths.c, src/main/common/maths.h, src/main/common/typeconversion.c, src/main/config/config.c, src/main/drivers/compass_hmc5883l.c, src/main/flight/altitudehold.c, src/main/flight/flight.c, src/main/flight/imu.c, src/main/flight/imu.h, src/main/flight/mixer.c, src/main/flight/navigation.c, src/main/io/display.c, src/main/io/ledstrip.c, src/main/io/rc_controls.c, src/main/io/serial_msp.c, src/main/mw.c, src/main/telemetry/frsky.c, src/test/unit/flight_imu_unittest.cc
Cleaned up IMU code and added tests.
=> Imu cleanup

src/main/blackbox/blackbox.c, src/main/common/maths.c, src/main/common/maths.h, src/main/common/typeconversion.c, src/main/drivers/compass_hmc5883l.c, src/main/flight/altitudehold.c, src/main/flight/flight.c, src/main/flight/mixer.c, src/main/flight/navigation.c, src/main/io/display.c, src/main/io/ledstrip.c, src/main/io/rc_controls.c, src/main/io/serial_msp.c, src/main/mw.c, src/main/telemetry/frsky.c, src/test/Makefile, src/test/unit/maths_unittest.cc
=> Added maths test.

.travis.sh, .travis.yml, src/test/Makefile
Slightly hacky, but tell me what you think :)
=> Running unit tests in travis.

src/main/flight/flight.c, src/main/io/serial_cli.c
MultiWii 2.3 PID controller 
set pid_controller = 3 (MultiWii 2.3 PID's)
MultiWii hybrid PID controller. Roll and pitch is using the MultiWii 2.2 algorithm and yaw is using the 2.3 algorithm. 
set pid_controller = 4 (MultiWii Hybrid PID's)
=> MultiWi 2.3 PID controller port

docs/PID tuning.md, src/main/config/config.c
@hydra 
The documentation update.
=> PID contoller documentation update (MultiWii23 and MultiWiiHybrid)

src/main/drivers/pwm_rx.c
this solution of issue #318. It has been tested as decribed in issue 318.
=> Detect failsafe for receivers that output a logic HIGH on signal loss.

docs/PID tuning.md
Add warning about the P_Level default value of 90 which will most likely result in loss of control in Angle Mode in PID Controller 1.
=> Update PID tuning.md

src/main/flight/pid.c
Aligned with Crashpilot1000 updates and flight tested
=> Fix for Harakiri PID 

src/main/io/serial_cli.c
Sample dump output:
```
servo 0 1020 2000 1500 30 -1
servo 1 1020 2000 1500 30 -1
servo 2 1020 2000 1500 100 -1
servo 3 1020 2000 1500 100 -1
servo 4 1020 2000 1500 100 -1
servo 5 1020 2000 1500 100 -1
servo 6 1020 2000 1500 100 -1
servo 7 1020 2000 1500 100 -1
```
Fixes #468
=> Add "servo" CLI command to get/set servo conf, and include in dump

docs/Battery.md
The tuning method for the parameters wasn't totally clear. As per http://www.rcgroups.com/forums/showpost.php?p=30778239&postcount=2957
=> Clarify Virtual Current Meter docs

build_docs.sh, docs/Safety.md
Add safety documentation immediately after the introduction section. Comes from #498.
=> Safety docs

docs/development/PID Internals.md
I started documenting PID itnernals, this PR is only to make review easier.
All comments are welcome.
=> Doc pid internals

docs/development/Hardware Debugging.md
Added reference to detailed guide in the wiki, and visual studio IDE setup
=> Update Hardware Debugging.md

docs/Spektrum bind.md
Added a description for connecting the SAT to a Flip32+ board
=> Update Spektrum bind.md

src/main/flight/pid.c
integer constrain function is limiting accuracy in Angel and Horizon mode ITerm value
=> Harakiri PID controller fix

Makefile, src/main/blackbox/blackbox.c, src/main/blackbox/blackbox_io.c, src/main/blackbox/blackbox_io.h, src/main/common/encoding.c, src/main/common/encoding.h, src/test/Makefile, src/test/unit/encoding_unittest.cc
Also adds a bit more Blackbox code documentation
=> Save around 300 bytes of flash by improving Blackbox field name storage

src/main/telemetry/hott.c
The first two bytes after initial Hott request are either 0x8080 (request for binary mode) or 0x7F0F (request for text mode).
The *useSoftserialRxFailureWorkaround* bool was introduced as the first byte 0x80 is read as 0x00 (softserail timing issue somewhere ?) and so to skip this first byte. The second byte (also 0x80) is correctly read.
In order to account for other Hott receivers and allow text_mode (in preparation), this PR enlarges the test on the requestID so the workaround process is no longer needed.
(but the timing issue observed with the highest bit ot the first byte after initial hott request is not solved)
=> HoTT check serial data improvement

src/main/sensors/initialisation.c
=> Fix invalid memory read during compass initialisation

docs/Mixer.md
No video yet, but hopefully this will be enough to get people headed in the right direction.
=> Servo tune documentation

docs/Inflight Adjustments.md
Adds separators between example images so that it's possible to tell what's what. It took me a a bit to realize what's happening here.
=> Update Inflight Adjustments.md

src/main/io/gps.c
Add NMEA $GPGSV packet decoding to give satellite PRN numbers and SNR.
Tidy up the NMEA code a little but it could do with a lot more in the
future..
Tested with my MTK GPS which outputs data as per the NMEA standard (http://www.trimble.com/OEM_ReceiverHelp/V4.44/en/NMEA-0183messages_GSV.html)
=> Add NMEA Signal Quality

docs/LedStrip.md
I've added the default LED colors to the documentation for indication and orientation modes.
=> Update LedStrip documentation from issue tracker 555

docs/Battery.md
I made a silly error with my last modification to this. :cry:
=> Fix error in VCM docs

docs/Gps.md, docs/Gps_-_Tested_Hardware.md
Moved GPS hardware list to new doc, and added working status for Ublox Neo-M8N.
=> GPS support and hardware split

src/main/blackbox/blackbox.c, src/main/blackbox/blackbox_io.c, src/main/blackbox/blackbox_io.h, src/main/common/printf.c, src/main/common/printf.h
@thenickdude, what do you think?
=> Improvement - blackbox

docs/Failsafe.md
Spellchecked docs & added 'feature FAILSAFE' to documentation. See #631
=> References cleanflight/cleanflight#631 - revised docs

docs/Gps_-_Tested_Hardware.md
Added a GPS receiver I verified to be working with CF on my quad
=> Update GPS tested hardware

docs/Cli.md
Preview of the new rendering of code blocks
=> Put CLI commands in code blocks so they appear in the markdown correctly

src/main/io/serial_cli.c
=> Ignore trailing spaces on CLI commands

src/main/io/serial_msp.c
New codes: MSP_SET_ARM_CONFIG, MSP_ARM_CONFIG, MSP_SET_LOOP_TIME, MSP_LOOP_TIME
Incremented minor version to 8.
=> Added new MSP codes to serial_msp.c

docs/Migrating from baseflight.md
Update docs with incorrect info for rssi_channel and add the missing renamed functionality.
=> Doc update

docs/development/PID Internals.md
=> Augment/improve PID Internals

src/main/telemetry/frsky.c
changed speed from cm/s to knots
=> Fixed speed according to frsky protocol

docs/development/Building in Mac OS X.md
Adding the correct way to generate the *.bin to use on CC3D-board.
This is my first time testing on how to create and use a PR in order to start to help out in the cleanflight code.
=> In order to make a CC3D.bin you need to add OPBL=yes.

docs/Battery.md
Added warning note to battery monitor docs to avoid Naze32 board destruction.
=> Update to Battery monitor docs

docs/Buzzer.md, src/main/blackbox/blackbox.c, src/main/config/runtime_config.c, src/main/config/runtime_config.h, src/main/flight/failsafe.c, src/main/flight/navigation.c, src/main/io/beeper.c, src/main/io/beeper.h, src/main/io/rc_controls.c, src/main/main.c, src/main/mw.c, src/main/sensors/acceleration.c, src/test/unit/altitude_hold_unittest.cc, src/test/unit/flight_imu_unittest.cc, src/test/unit/rc_controls_unittest.cc
This the "Port of refactored beeper code #669" modification applied to version 1.8.1 (4/4/2015) of the code.  See the previous PR for info:  http://github.com/cleanflight/cleanflight/pull/669
Code and hex test file are also here: http://www.etheli.com/CF/refactoredBeeperCode
--ET
=> Port of refactored beeper code 181_1

docs/Battery.md
See diffs -- I made a pass to fix typos, clean up language, copy edit, and clarify various items.
=> Update Battery.md w/ copy edits & typo fixes

docs/Display.md
Link to banggood was broken and now fixed. Added a second oled to from Banggood.
=> Fixed broken link to banggood

docs/Battery.md
fixes #740 
@dkisselev  Per your comments on #814 about calculating `current_meter_scale`, could you eyeball and see if this addresses your comments?
=> Battery.md:  clarify current_meter_scale

CONTRIBUTING.md, README.md, docs/development/Development.md
Having just started finding my way around all the documentation, I found useful development information spread across three documents.  I have consolidated the information into /docs/development/Development.md
It looks like I've taken an axe to it but I think it will help to keep all the information in one place.
=> Consolidated development info into Development.md

docs/development/Development.md
May help someone in the future :)
=> Git command to update your fork

src/main/telemetry/frsky.c
As mentioned in #486 and on IRC yesterday, heading is only displayed when a GPS fix is available (the behaviour on my Taranis appears to be if the lat/long are zero then the heading doesn't update).
The issue could be worked around by setting `frsky_default_lattitude` and `frsky_default_longitude` to a non zero value, if you happened to know doing that would have this side-effect.
This PR has FrSky telemetry always send a location of 1 deg north/1 deg east when a GPS sensor isn't available (it's kind of a hack, but if you have no GPS then the lat/long is going to be meaningless anyway).
(I've stacked this on top of PR #854, let me know if you want it rebased)
=> Frsky telemetry heading without GPS

docs/Rx.md
The text mentioned the "Serial Chapter" which isn't really helping you at all (IMHO), I removed that. The stuff you actually want is just a few paragraphs down in the same document....
=> Fix documentation about 16 channel S.Bus to be clearer.

docs/Modes.md, docs/PID tuning.md
If you want doc changes differently or not at all please notify.
=> Doc edits I found and fixed while setting up some boards.

docs/PID tuning.md
Changed documentation for 1.9.0
=> PID1 Horizon Doc changed + TPA doc adjusted.

docs/Blackbox.md, src/main/blackbox/blackbox.c
=> Fix Blackbox arming beep time logging

docs/Board - AlienWii32.md, docs/Spektrum bind.md, src/main/config/config.c
Updated configuration defaults
Documentation updates AlienWii and Spektrum bind
=> AlienWii32 updates

lib/main/CMSIS/CM3/CoreSupport/core_cm3.c, src/main/blackbox/blackbox_io.h, src/main/drivers/display_ug2864hsweg01.c, src/main/drivers/timer.c, src/main/flight/altitudehold.c, src/main/flight/imu.c, src/main/io/beeper.c, src/main/io/display.c, src/main/io/ledstrip.c, src/main/io/rc_controls.c, src/main/io/serial_msp.c, src/main/main.c, src/main/sensors/barometer.c, src/main/sensors/initialisation.c, src/main/sensors/initialisation.h, src/main/sensors/sonar.c, src/main/version.c
I had a hack with building Cleanflight with G++.  This patch set fixes bugs like missing includes and duplicate definitions that were found on the way.
Feel free to skip the designated initialiser changes.
=> various: tidy up various things found when building with a C++ compiler.

src/main/blackbox/blackbox.c, src/main/blackbox/blackbox.h, src/main/blackbox/blackbox_fielddefs.h
Fixes #684 
Due to code improvements, code size shrinks by 50 bytes with this addition.
=> Blackbox - Add logging for flight state, flight mode, and failsafe state

src/main/common/maths.c, src/main/common/maths.h, src/main/flight/imu.c, src/main/flight/navigation.c, src/main/mw.c, src/test/unit/maths_unittest.cc
This was asked for by @thenickdude in #940.
=> Ported fast trigonometry functions over from @Crashpilot1000 Harakiri

src/main/common/maths.c
This is to continue what was started in #1092.
=> Modify and improve fast trigonometry

docs/Gps.md
Small modification for the type of GPS (NEO-6M).
=> Update GPS Doc

docs/Mixer.md
I hope I am right in thinking that cmix should be mmix here.
=> Change cmix to mmix on one line

src/main/telemetry/frsky.c
Comment looks correct but code didn't match.
Reported here:
https://github.com/opentx/opentx/issues/2644
=> GPS speed was 10x too big on frsky telemetry

src/main/config/config.c, src/main/sensors/battery.c, src/main/sensors/battery.h, src/test/unit/battery_unittest.cc
Ability to change the resistor divider ratio, as well as ability to multiply scale for small voltages.
Broken out of original pull request [2/3]
=> Modified VBatt functionality to enable better precision.

src/main/drivers/pwm_rx.c, src/main/drivers/pwm_rx.h, src/main/io/display.c, src/main/rx/rx.c, src/main/rx/rx.h, src/main/rx/spektrum.c, src/test/unit/rx_ranges_unittest.cc, src/test/unit/rx_rx_unittest.cc
Large code re-organization which separates some key tasks in the rx code.
Tests need to be updated before merging.
Tested with X8R in SBus and PWM, and Spek Sat.
See #1190 and #1207
=> Failsafe - Fixes for RX loss detection.

README.md
Minor typo fix on final bullet point in new features list
=> Typo fix on Readme.md

src/main/io/serial_cli.c
=> Prevent arming when in CLI mode

docs/development/Development.md
Fixes two typos in the Development.md file.
=> Docs typos

docs/Mixer.md
Fixing servo mixing tables presentation in doc
=> Fix servo mixing tables

docs/Mixer.md
Added notes on how to make a custom airplane configuration that supports differential thrust.
=> Custom Airplane with Differential Thrust

docs/Gtune.md
It was a little bit hard to read with only two paragraphs, and looking at the raw .md file it was clear that having just two paragraphs was not the original intention.
=> Little cleanup in Gtune documentation

src/main/drivers/adc_stm32f30x.c
Fixes issue with automatically adding external ADC which fixes current sensor ADC.
=> F3 ADC fix.

src/main/telemetry/hott.c
This is a proposal to solve issue #1413.
=> Fix Hott telemetry timing issue

src/main/target/SPARKY/target.h
confirmed the wrong compass direction
=> Correcting wrong compass alignment reported in #1407

build_docs.sh
Replaced Autotune with Gtune
Added Boards:
ColibriRace
Paris Air Hero 32
RMDO
SPRacingF3
=> Update build_docs.sh with New Docs

docs/Board - RMDO.md, src/main/io/serial_1wire.c, src/main/io/serial_msp.c, src/main/target/RMDO/target.h, src/main/target/SPARKY/target.h, src/main/target/STM32F3DISCOVERY/target.h
Tested with Naze and RMDO board
Discuss: https://github.com/cleanflight/cleanflight/pull/1246
=> Fix 1wire pass through for F3 + target config changes

src/main/telemetry/hott.c
This is related to issue #1461 and fix bug on speed unit conversion.
=> Fix bug on Hott GPS speed

src/main/config/config.c
Slightly improved defaults for luxfloat
=> Luxfloat defaults

src/main/io/serial_cli.c
e.g. ON/OFF instead of 1/0.
There is additional value in this for the onscreen configuration menus. See #792
=> Support get/set configuration values by name.

src/main/mw.c
See this issue:
https://github.com/cleanflight/cleanflight/issues/1019
=> Decreased MAG_HOLD deadband to 15

README.md, src/main/common/atomic.h, src/main/drivers/sonar_hcsr04.c, src/main/drivers/sonar_hcsr04.h, src/main/flight/altitudehold.c, src/main/mw.c, src/main/sensors/sonar.c, src/main/sensors/sonar.h, src/test/Makefile, src/test/unit/altitude_hold_unittest.cc, src/test/unit/flight_imu_unittest.cc, src/test/unit/sonar_unittest.cc
Corrected spelling in comments. Minor improvements to comments."
=> Sonarcleanup - replaced Sonar magic numbers with #defines. First cut of sonar test code.

docs/Failsafe.md, src/main/config/config.c, src/main/flight/failsafe.c, src/main/flight/failsafe.h, src/main/io/serial_cli.c, src/main/io/serial_msp.c, src/main/rx/rx.c
These are required modifications for the new failsafe TAB in the configurator.
Also includes some some code fixes and documentation update, see commit message.
=> Failsafe - added support for failsafe tab in configurator

src/test/unit/flight_imu_unittest.cc
This is required to get prepared to merge faster (but less precise) triginometry and more improvements to IMU.
=> Quaternion IMU unit test update

src/main/flight/altitudehold.c, src/main/flight/imu.h, src/main/sensors/sonar.c, src/main/sensors/sonar.h, src/test/Makefile, src/test/unit/sonar_unittest.cc
New IMU is able to provide true tilt angle, this PR uses it for sonar calculations.
=> Improve sonar compatibility with new IMU

src/main/io/serial_cli.c
=> FlySky i-Bus receiver CLI bug fixed

src/main/flight/altitudehold.c
Fixes issue #1598: Incorrect calculation of altitude when transitioning from sonar to baro.
=> Fixed issue 1598.

src/main/flight/pid.h
Changed to use enum instead of #define. Fixes https://github.com/cleanflight/cleanflight/issues/1649
=> Fix for issue 1649

docs/Rx.md
Added table of channel numbers and names.
=> Updated Receivers documentation

src/main/drivers/accgyro_l3gd20.c, src/main/drivers/adc_stm32f30x.c, src/main/telemetry/frsky.c
Fix problems causing warnings in compilation.
=> Fix compilation warnings

docs/Sonar.md
Added specific values for sonar altitude and attitude. Added sonar connections for SPRacingF3. Updated CC3D sonar connections to include RC pin numbers.
=> Minor additions to sonar documentation

README.md
Some small typo/editing and formatting fixes, no content changes.
=> Clean up the README (typos, formatting, small edits)

src/main/telemetry/hott.h
=> Typo in hott.h

src/main/sensors/sonar.c
On some surfaces the sonar can get reflections and measurement errors.
This PR adds simple median filtering to correct this. 
The median is taken over 5 samples, when the sonar is in range.
=> Sensors - Sonar - Apply median 5 filter on readings

src/main/drivers/serial.c
Note: this is likely not the best solution, we can investigate further
in due course.
See  #1753
=> Prevent serial tx buffer overflow.

src/main/io/serial_cli.c
=> gyro_lpf change 256hz to OFF

docs/Boards.md, docs/Configuration.md, docs/Failsafe.md, docs/Getting Started.md, docs/Introduction.md, docs/Safety.md
Added links. Fixes issue #1755
=> Added links to documentation. Fixed one spelling mistake.

docs/Telemetry.md
Telemetry docs updated with SoftSerial solution for F1 and F3 targets for FrSky S.Port Telemetry
=> Smartport telemetry docs

src/main/main.c, src/main/scheduler.c, src/main/scheduler.h, src/main/scheduler_tasks.c, src/test/Makefile, src/test/unit/scheduler_unittest.cc
Just one very basic test at the moment: enable one task, call the scheduler and check the task has run and has had its properties updated.
But I've done the yak shaving. I plan to add further tests in the near future.
By the way, I love this new scheduler!
=> Initial submission of scheduler unittest.

src/main/config/config.c, src/main/flight/mixer.c, src/main/flight/mixer.h, src/main/flight/pid.c, src/main/flight/pid.h, src/main/io/serial_cli.c, src/main/mw.c
Here the new code from discussions in https://github.com/cleanflight/cleanflight/pull/1766
@ledvinap @hydra
=> Airmode Cleanup fixes / optimalisations

src/main/flight/mixer.c, src/main/flight/pid.c, src/main/mw.c
@hydra 
Merge this one. See comments and discussions in #1766
=> Airmode #1766 Cleanups and corrections

docs/Spektrum bind.md
Updated documentation:  Added newly discovered Spektrum bind parameter.  Added new tested hardware combination.  Removed dead link to OpenPilot wiki.
=> Update Spektrum Bind Documentation - Spektrum bind.md

docs/Rx.md, src/main/rx/ibus.c
Per #1593 added documentation for i-BUS in rx document.
=> Updated Rx.md for i-BUS

src/main/sensors/acceleration.c, src/main/sensors/acceleration.h, src/main/sensors/boardalignment.c, src/main/sensors/boardalignment.h, src/main/sensors/compass.c, src/main/sensors/compass.h, src/main/sensors/gyro.c, src/main/sensors/gyro.h, src/test/unit/alignsensor_unittest.cc, src/test/unit/flight_imu_unittest.cc, src/test/unit/serial_msp_unittest.cc
See discussion here:
https://github.com/cleanflight/cleanflight/issues/1818
=> Fix sensors saturation by converting to int32_t (Fix for #1818)

src/test/unit/platform.h, src/test/unit/ws2811_unittest.cc
Fixes issue https://github.com/cleanflight/cleanflight/issues/1846
=> Made use of WS2811_DMA_TC_FLAG consistent.

src/main/rx/ibus.h, src/main/rx/msp.h, src/main/rx/pwm.h, src/main/rx/rx.c, src/main/rx/sbus.h, src/main/rx/spektrum.h, src/main/rx/sumd.h, src/main/rx/sumh.h
Fixes issue https://github.com/cleanflight/cleanflight/issues/1844
=> Moved function declarations out of rx.c into relevant header files.

docs/Telemetry.md, src/main/telemetry/smartport.c
Remove some code not needed anymore due to OpenTX changes and update documentation accordingly
=> Remove unecessary telemetry code

docs/Mixer.md
I added an example and a few words that it's important to make the commands in order to work. I hope I have written it clearly enough.
=> Noted that mmix commands bust be made in order.

src/main/io/serial_cli.c, src/main/scheduler.c, src/main/scheduler.h
Also added task frequency.
This fixes issue https://github.com/cleanflight/cleanflight/issues/1955.
=> Improved formatting of tasks statistics in CLI.

src/main/config/parameter_group.h, src/test/Makefile
Needs a bit of tidying, but it works.
=> Fix parameter groups tests under running on OSX.

src/main/io/serial_cli.c, src/main/io/serial_msp.c
Also refactor cli variables slightly to reduce code duplication
=> Fix possibly uninitialized variable warnings

Makefile, src/main/config/config_unittest.h, src/main/flight/pid.c, src/main/flight/pid.h, src/main/flight/pid_luxfloat.c, src/main/flight/pid_mw23.c, src/main/flight/pid_mwrewrite.c, src/test/Makefile
Moved each PID controller into its own source file, for better clarity and as a precursor to further unit tests.
=> Moved each PID controller into its own source file

src/main/io/serial_4way.c, src/main/io/serial_4way.h, src/main/io/serial_4way_avrootloader.c, src/main/io/serial_4way_avrootloader.h, src/main/io/serial_4way_stk500v2.c, src/main/io/serial_4way_stk500v2.h, src/main/io/serial_msp.c
Another attempt to revert my mistake, now commit-by-commit, should revert everything correctly
=> Revert cleanup 4way 2

src/main/io/serial_4way.c, src/main/io/serial_4way.h, src/main/io/serial_4way_avrootloader.c, src/main/io/serial_4way_avrootloader.h, src/main/io/serial_4way_impl.h, src/main/io/serial_4way_stk500v2.c, src/main/io/serial_4way_stk500v2.h, src/main/io/serial_msp.c
4way-if is working on silabs BLHeli bootloader and AVR SimonK bootloader
Can someone test AVR-BLHeli bootloader? I'll get to it later ..
=> Cleanup 4way-if

src/main/scheduler_tasks.c, src/test/unit/scheduler_unittest.cc
Fixed issue https://github.com/cleanflight/cleanflight/issues/1946 by setting `TASK_ACCEL` `desiredPeriod` to 1000 (1ms).
Also added comments to other desired periods and changed `TASK_SONAR` desired period to 70ms to match sonar trigger interval.
=> Changed TASK_ACCEL desiredPeriod to 1ms.

src/main/mw.c
Proposed G-Tune fix. Not tested yet.
https://github.com/cleanflight/cleanflight/issues/2074
https://github.com/cleanflight/cleanflight/issues/2020
=> Fix G-Tune

docs/PID tuning.md
Also took the opportunity to do some minor editing.
This is just a minimal edit to reflect the changes to PID_LUXFLOAT, it could still be improved.
=> Update of PID documentation to reflect PID_LUXFLOAT changes

src/main/mw.c
Currently, TPA and throttle expo are updated every iteration of PID main loop. With new RX data available only at 50Hz this means that the same operations are repeated for the same data.
With looptime 2000 the same output is computed 10 times before it changes. 
This pull requests updates those coefficients only when new RX data is available
=> TPS, pid scaling and throttle expo updated outside main PID loop

src/main/io/display.c, src/main/io/display.h
Also changed so battery page is not displayed if neither FEATURE_VBAT or FEATURE_CURRENT_METER is enabled.
=> Added PIDs to OLED display profile page. Added TASKS page.

src/main/config/config.c, src/main/flight/mixer.c, src/main/flight/mixer.h, src/main/main.c, src/test/unit/flight_mixer_unittest.cc
Removed unused `#includes`.
Grouped `#ifdef` code together to avoid repeated tests of same condition.
Made some functions static.
Cleaned up some related `#ifdef USE_SERVOS` function declaration and definition madness.
=> Cleanup - further tidying of config.c

Makefile, src/main/target/MOTOLAB/target.h
=> Add MPU6000 code to MOTOLAB target

src/main/drivers/gpio.h, src/main/drivers/gpio_stm32f10x.c, src/main/drivers/gpio_stm32f30x.c
Addresses issue https://github.com/cleanflight/cleanflight/issues/1797
=> Fixed const correctness of gpioInit functions.

src/main/io/msp_protocol.h, src/main/io/serial_msp.c, src/test/unit/serial_msp_unittest.cc
Add HDOP value to MSP_RAW_GPS
cleanflight/cleanflight-configurator issue 218
=> MSP_RAW_GPS: add GPS_hdop

src/main/mw.c
This fixes the alt hold bug for fixed wing aircraft as discussed in PR https://github.com/cleanflight/cleanflight/pull/2171
=> Fixed handling of rcCommands[] in main pid loop.

src/main/io/msp.c
=> Implement BoxAirMode flag in MSP_STATUS

docs/development/Building in Fedora.md
Instructions for building on Fedora linux, also works on Ubuntu.
=> Added doc for building on Fedora linux

docs/Battery.md
=> Documentation update Battery.md after some CLI changes

docs/Controls.md
- Doc: list disabled arming conditions
- ~~Add SPRF3Evo to travis build targets~~
=> Doc: disabled-arming conditions

.travis.sh, Makefile, src/test/Makefile
Makefile will pass -Werror to gcc when building Travis Pull
request. Branches are build normally.
This PR should fail now - there are warnings in master
=> Fail Travis build when PR contains warnings

.travis.sh, Makefile, src/test/Makefile
This should help with make test failing. But something more elegant will be nice ...
=> Fix submakefile inheriting CC etc

.gitattributes
=> Use lf EOL for travis and make files

docs/Gps.md
I added a align_mag addition for UBLOX Neo-7 in the docs.
This resolves #1123
=> Align_mag addition for UBLOX Neo-7 in the docs

docs/Board - SPRacingF3.md
Added a single letter. Corrected an "of" to "off."
=> Correcting a word in doc 'Board - SPRacingF3.md'

Vagrantfile
Provisioning succeeds with this change.
#2250
=> Fixing vagrant provisioning error.

src/main/fc/cleanflight_fc.c, src/main/fc/rc_curves.c, src/main/fc/rc_curves.h
This addresses item "Move RC lookup out of mw.c into rc_curves.c" of issue https://github.com/cleanflight/cleanflight/issues/2213
=> Fixed rc_lookup so all implemetation detail is local to rc_curves.c

src/main/target/SPRACINGF3OSD/target.h
Don’t know what the bus sw is, but looks like a simple typo.
=> B is most likely

src/main/fc/fc_tasks.c
=> Fix for issue 2319 run TASK_GPS at 100Hz

src/main/msp/msp_protocol.h
This should help avoid future conflicts.
There are still outstanding conflicts to be resolved, see issue https://github.com/cleanflight/cleanflight/issues/2306
=> Updated MSP protocol with betaflight and iNav commands

src/main/drivers/pwm_mapping.c
This allows Tricopters on the SP Racing F3 Evo
#2243
=> Adding servo support for F3 Evo.

docs/LedStrip.md, src/main/fc/msp_server_fc.c, src/main/io/ledstrip.c, src/main/io/ledstrip.h, src/main/io/serial_cli.c, src/main/msp/msp_protocol.h, src/main/sensors/battery.c, src/test/unit/ledstrip_unittest.cc, src/test/unit/msp_fc_unittest.cc
Fixes #287 with a new function 'L' that binds LED hue to battery level.
Depends on merge of @ledvinap's LED cleanup.
@skaman82, configurator update will follow.
=> LED strip rework + battery + larson scanner + blink on landing

src/main/drivers/pwm_mapping.c, src/main/drivers/pwm_mapping.h, src/main/main.c
I'm submitting this PR on behalf of @jflyper who kindly sent me the code.
Adds separate gpios for trigger and echo.
=> Code from jflyper. Fixes issue 1868

src/main/drivers/accgyro_mpu6500.c
Add MPU6500 gyro temperature reading, assuming the cleanflight temperature should be expressed in degree centigrades (not documented anywhere or ?).
Using decigrades would make more sens since the temperature is stored in a short. Maybe some other sensors do this since in the frsky.c telemetry, the temperature is divided by 10 before sending. No info in the git history about this.
=> accgyo_mpu6500: add temperature reading.

.travis.yml, Makefile
however, see this if you use cygwin
https://github.com/betaflight/betaflight/issues/774
(basically, cygwin + ccache = fail)
=> Enable ccache

src/main/fc/boot.c, src/main/io/gps.c
As in iNav.
Addresses issue https://github.com/cleanflight/cleanflight/issues/2211
=> Add initialisation delays to allow GPS to power up

docs/Modes.md
Added a basic explanation of how the default RATE mode works and the difference between ANGLE and HORIZON.
To address #2356
=> Added basic auto-leveled flight modes explanation

docs/development/Building in Windows.md
I added information about Bash on Windows 10, a new feature in Windows 10 that I found to be super helpful whenever working with based Linux. Bash for Windows 10 runs a copy of Ubuntu alongside your Windows OS and has great synergy between the two OSs. You can use just about any command line tool from the bash terminal, which makes building and debugging great just as it is on Ubuntu.
It is much cleaner and easier to use than cygwin, I would recommend it to anyone running Windows 10.
=> Docs: Adding Information About Building on Bash for Windows 10

docs/development/CodingStyle.md
For discussion.
Replacing the old Baseflight version, adding new input and some structure.
Been thinking about it sometimes since #2191.
Became longer than expected...
Probably not perfect but now all in one md file.
=> Coding Style document

docs/Telemetry.md, src/main/telemetry/smartport.c
Either an alternative or a complement to https://github.com/cleanflight/cleanflight/pull/1927
Please read the discussion on #1927 thread :)
=> Cell volt on a4

docs/development/Development.md
Replace link to old style
Remove old items 3 and 5 due to duplication
plus some small things
=> Update developer documentation.

src/main/telemetry/smartport.c
=> Smart Port telemetry GPS ground speed unit is not applicable. (#2166)

src/main/drivers/bus_i2c_stm32f10x.c
Fix for too aggressive error handling when a NAK (a normal bus event) was treated as a bus error and resulted in bus "unstick". Additionally, unstick was only clocking out 8 bits, while in most cases it should be 9 (8 bit data and ACK/NAK) and clock was followed by an empty trasnaction (START-STOP with no clock).
See https://github.com/iNavFlight/inav/pull/668
=> Fix I2C bus error handling for F1 targets

src/main/blackbox/blackbox.c, src/main/drivers/compass_hmc5883l.h, src/main/drivers/exti.h, src/main/drivers/io.h, src/main/drivers/sonar_hcsr04.h, src/main/fc/cleanflight_fc.c, src/main/fc/config.c, src/main/fc/rc_adjustments.c, src/main/fc/rc_adjustments.h, src/main/fc/rc_controls.h, src/main/flight/altitudehold.h, src/main/flight/navigation.h, src/main/io/display.c, src/main/io/serial_cli.c, src/main/rx/rx.c, src/main/telemetry/frsky.c, src/main/telemetry/mavlink.c, src/main/telemetry/smartport.c
Reduced dependencies by moving some #includes out of header files into .c files.
=> Tidied header files and reduced dependencies

src/main/drivers/nvic.h, src/test/Makefile, src/test/unit/nvic_unittest.cc, src/test/unit/platform.h
Fixes #2457
@asbird found this bug, thanks.
=> Fix NVIC_PRIORITY_SUB to return correct bits

src/main/rx/ibus.c
ibusFramePosition was not set to zero after finishing frame
=> ibusFramePosition update

src/main/drivers/transponder_ir.c, src/main/drivers/transponder_ir.h
Tested on F3/F4 targets using real iLaps receiver hardware.
=> Fix F4 transponder transponder.

src/main/drivers/transponder_ir.c, src/main/drivers/transponder_ir.h, src/main/fc/fc_msp.c, src/main/io/transponder_ir.c, src/main/io/transponder_ir.h
See https://github.com/cleanflight/cleanflight/pull/2580
=> CF/BF - Cleanup transponder config after Arctimer merge.

src/main/fc/cli.c
From BF https://github.com/betaflight/betaflight/pull/2877
Not sure if the problem description in the BF PR is correct since it affects the CLI, not the MSP commands.
=> fixed blackbox devicelist

docs/Battery.md
Formula changed to reflect current sensor scale as of Betaflight 3.1.7
=> Update to current sensor calibration with charger

docs/PID tuning.md
Sync documentation for [BF PR 2570](https://github.com/betaflight/betaflight/pull/2570)
horizon_tilt_mode SAFE|EXPERT
changed to
horizon_tilt_expert_mode OFF|ON
--ET
=> Doc update for horizon_tilt_expert_mode

docs/Customized Version.md
Updated doc. The file `common.h` is now `common_fc_pre.h`.
=> Update doc: common.h file is now common_fc_pre.h

docs/Telemetry.md
Updated Telemetry inversion parameter from telemetry_inversion to tlm_inversion.
Not sure if any of the other parameters have changed.
=> Updated Telemetry Inversion parameter

docs/Telemetry.md
Version 3.0 changed the mentions of variable telemetry_inversion to tml_inversion
=> Updating cli variable telemetry_inversion to tlm_inversion

src/main/osd_slave/osd_slave_init.c
broken by fdfe9e8af355ee70edecabe206536ad95fc69b6e
=> CF/BF - Fix OSD slave serial port initialisation

docs/Board - Naze32.md
Update note about GPS is not supported with naze32
=> Create Board - Naze32.md

docs/PID tuning.md
The description was not accurate (anymore) to Cleanflight 2. I changed the text accordingly.
=> CHG PID tuning Angle/Horizon GUI text labels

src/main/fc/fc_msp.c
=> CF/BF - Fix missing initialiser in flightModeFlags

src/main/fc/settings.c, src/main/io/osd.c, src/main/io/osd.h, src/main/target/SPRACINGF4EVO/target.h
Add option to display data from ESC sensor: temperature + speed.
=> OSD: display temperature and speed from ESC sensor.

src/main/config/config_eeprom.c, src/main/fc/cli.c, src/main/target/SITL/parameter_group.ld, src/main/target/SITL/target.c, src/main/target/SITL/target.h
fix EEPROM problem in SITL by merge ledvinap's EEPROM in RAM.
=> Use variable for eeprom emulation in SITL

src/main/drivers/system_stm32f7xx.c, src/main/flight/imu.c, src/main/io/vtx.c
cherry-picked some recent fixes.
=> Betaflight changes

src/main/drivers/pwm_output.h, src/main/drivers/pwm_output_dshot_hal.c, src/main/target/stm32f7xx_hal_conf.h, src/main/target/system_stm32f7xx.c
This reverts commit fa3c7e0833ccc5ed535ba15491f4e34b19671173.
Broken, see comments on https://github.com/betaflight/betaflight/pull/5237
=> Revert "Rewritten F7 dshot to LL (draft)"

Makefile
Looks like it's been broken for a while now.
=> Fix SREC creation.
